Repository ydb-platform/ydb-go-sdk, pull requests merged in 2022-12, with the labels that each got.

#478 Supported internal allocator in `{session,statement}.Execute` for decrease GC usage
  CHANGELOG.md
  internal/allocator/allocator.go
  internal/allocator/allocator_go1.18.go
  internal/coordination/client.go
  internal/credentials/static.go
  internal/discovery/discovery.go
  internal/grpcwrapper/rawtopic/describe_topic.go
  internal/ratelimiter/client.go
  internal/scheme/client.go
  internal/scripting/client.go
  internal/table/data_query.go
  internal/table/keep_in_cache.go
  internal/table/keep_in_cache_test.go
  internal/table/session.go
  internal/table/session_test.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/table/transaction_test.go
  table/options/options.go
  table/table.go
Labels: enhancement

#473 Remove a mistake
  CHANGELOG.md
  topic/README.md
Labels: no changelog

#484 * Supported `table.Transaction.WithCommit()` method for execute query and auto-commit after
  CHANGELOG.md
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  table/example_test.go
  table/table.go
  table/table_e2e_test.go
Labels: enhancement

#495 added codecov.yml
  codecov.yml
Labels: no changelog

#496 Refactoring of internal retry types
  .github/workflows/lint.yml
  go.mod
  go.sum
  internal/operation/status.go
  internal/retry/check.go
  internal/retry/mode.go
  internal/xcontext/idempotent.go
  internal/xerrors/check.go
  internal/xerrors/operation.go
  internal/xerrors/retryable.go
  internal/xerrors/transport.go
  internal/xerrors/type.go
  internal/xerrors/xerrors.go
  internal/xsql/badconn/badconn.go
  internal/xsql/badconn/badconn_go1.18.go
  internal/xsql/badconn/badconn_go1.18_test.go
  internal/xsql/conn.go
  internal/xsql/tx.go
  retry/errors_data_test.go
  retry/mode.go
  retry/retry.go
  retry/sql_test.go
Labels: no changelog

#501 add examples
  topic/topicoptions/topicoptions_reader_example_test.go
  topic/topicoptions/topicoptions_writer_example_test.go
Labels: no changelog

#504 Reverted tx.WithCommit() and added options.WithCommit() option of ExecuteDataQuery
  .golangci.yml
  CHANGELOG.md
  internal/cmd/gtrace/writer.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/table/transaction_test.go
  log/table.go
  table/example_test.go
  table/options/options.go
  table/table.go
  table/table_e2e_test.go
  trace/table.go
  trace/table_gtrace.go
Labels: bug, enhancement
