Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-05, with the labels that each got.

#716 Update README.md for slo run
  README.md
Labels: no changelog, tests

#719 fix docker image tags
  .github/workflows/tests.yml
Labels: refactoring

#720 replace !fast => integration
  .github/workflows/tests.yml
  tests/integration/README.md
  tests/integration/connection_secure_test.go
  tests/integration/connection_test.go
  tests/integration/connection_with_compression_test.go
  tests/integration/database_sql_get_all_tables_test.go
  tests/integration/database_sql_get_column_type_test.go
  tests/integration/database_sql_get_columns_test.go
  tests/integration/database_sql_get_index_columns_test.go
  tests/integration/database_sql_get_indexes_test.go
  tests/integration/database_sql_get_primary_keys_test.go
  tests/integration/database_sql_get_tables_test.go
  tests/integration/database_sql_is_column_exists_test.go
  tests/integration/database_sql_is_primary_key_test.go
  tests/integration/database_sql_is_table_exists_test.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/database_sql_scheme_test.go
  tests/integration/database_sql_static_credentials_test.go
  tests/integration/database_sql_test.go
  tests/integration/discovery_test.go
  tests/integration/helpers_test.go
  tests/integration/monitoring_test.go
  tests/integration/ratelimiter_test.go
  tests/integration/scripting_test.go
  tests/integration/static_credentials_test.go
  tests/integration/sugar_make_remove_recursive_test.go
  tests/integration/table_bulk_upsert_test.go
  tests/integration/table_bulk_upsert_with_compression_test.go
  tests/integration/table_create_table_description_test.go
  tests/integration/table_create_table_partitions_test.go
  tests/integration/table_data_query_issue_row_col_test.go
  tests/integration/table_data_query_with_compression_test.go
  tests/integration/table_interval_from_duration_test.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/table_null_type_test.go
  tests/integration/table_scan_error_test.go
  tests/integration/table_scan_query_with_compression_test.go
  tests/integration/table_split_ranges_and_read_test.go
  tests/integration/table_test.go
  tests/integration/table_tx_control_test.go
  tests/integration/table_tx_lazy_test.go
  tests/integration/table_type_to_string_test.go
  tests/integration/table_tz_timestamp_test.go
  tests/integration/table_unexpected_null_while_parse_nil_json_document_value_test.go
  tests/integration/topic_cdc_reader_test.go
  tests/integration/topic_client_test.go
  tests/integration/topic_grpc_stopper_helper_test.go
  tests/integration/topic_partitions_balanced_test.go
  tests/integration/topic_read_messages_test.go
  tests/integration/topic_read_writer_test.go
  tests/integration/topic_stress_test.go
Labels: no changelog, refactoring

#721 clockwork
  internal/table/client.go
  internal/table/client_test.go
  internal/xsql/connector.go
Labels: no changelog

#698 feat: use golangci-lint for check examples code
  .github/workflows/lint.yml
  .golangci.yml
  examples/basic/database_sql/data.go
  examples/basic/database_sql/main.go
  examples/basic/database_sql/series.go
  examples/basic/gorm/main.go
  examples/basic/gorm/models.go
  examples/basic/native/series.go
  examples/ddl/ddl.go
  examples/describe/main.go
  examples/read_table/orders.go
  examples/serverless/healthcheck/service.go
  examples/serverless/url_shortener/main.go
  examples/serverless/url_shortener/service.go
  examples/topic/cdc-cache-bus-freeseats/database.go
  examples/topic/cdc-cache-bus-freeseats/main.go
  examples/topic/cdc-cache-bus-freeseats/webserver.go
  examples/topic/cdc-fill-and-read/cdc-reader.go
  examples/topic/cdc-fill-and-read/main.go
  examples/topic/cdc-fill-and-read/tables.go
  examples/topic/topicreader/stubs.go
  examples/topic/topicreader/topicreader_advanced.go
  examples/topic/topicreader/topicreader_show.go
  examples/topic/topicreader/topicreader_trace.go
  examples/topic/topicwriter/topicwriter.go
  examples/ttl/series.go
Labels: no changelog, refactoring

#705 refactoring of log
  CHANGELOG.md
  connection.go
  internal/logger/level/level.go
  internal/logger/log.go
  internal/logger/options.go
  internal/xtest/logger.go
  log/context.go
  log/context_test.go
  log/coordination.go
  log/discovery.go
  log/driver.go
  log/field.go
  log/field_test.go
  log/join.go
  log/join_test.go
  log/level.go
  log/log.go
  log/logger.go
  log/logger_test.go
  log/loglevel.go
  log/options.go
  log/ratelimiter.go
  log/retry.go
  log/scheme.go
  log/scripting.go
  log/sql.go
  log/table.go
  log/topic.go
  logger_options.go
  options.go
  tests/integration/connection_secure_test.go
  tests/integration/connection_test.go
  tests/integration/connection_with_compression_test.go
  tests/integration/discovery_test.go
  tests/integration/helpers_test.go
  tests/integration/monitoring_test.go
  tests/integration/ratelimiter_test.go
  tests/integration/scripting_test.go
  tests/integration/static_credentials_test.go
  tests/integration/table_create_table_description_test.go
  tests/integration/table_create_table_partitions_test.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/table_split_ranges_and_read_test.go
  tests/integration/table_test.go
  tests/integration/table_tx_lazy_test.go
  tests/integration/topic_read_writer_test.go
  trace/details.go
Labels: refactoring

#727 update gorm-driver
  examples/go.mod
  examples/go.sum
  tests/slo/go.mod
  tests/slo/go.sum
Labels: no changelog

#730 build(deps): bump codecov-action v2 to v3
  .github/workflows/tests.yml
Labels: no changelog

#731 fix: slo parallel collision
  .github/workflows/slo.yml
Labels: bug, no changelog

#729 ci: run examples/basic on CI
  .github/workflows/breaking.yml
  .github/workflows/examples.yml
  examples/basic/database_sql/main.go
  examples/basic/gorm/main.go
  examples/basic/native/main.go
  examples/go.mod
  examples/go.sum
Labels: no changelog, CI

#733 feat: run examples/basic/gorm for postgres and sqlite every PR
  .github/workflows/examples.yml
  examples/basic/gorm/main.go
  examples/go.mod
  examples/go.sum
Labels: no changelog

#734 Update README.md
  README.md
Labels: no changelog

#740 Update README.md
  README.md
Labels: documentation

#737 chore(examples): remove NOT NULL non-PrimaryKey columns from basic/gorm
  examples/basic/gorm/models.go
Labels: no changelog

#744 ci: add ydb 23.2 to integration tests
  .github/workflows/examples.yml
  .github/workflows/tests.yml
Labels: no changelog, CI, tests

#748 ci: add label to skip slo tests
  .github/workflows/slo.yml
Labels: no changelog, no slo

#752 (example): basic example via Xorm
  .github/workflows/examples.yml
  examples/basic/xorm/README.md
  examples/basic/xorm/data.go
  examples/basic/xorm/main.go
  examples/basic/xorm/models.go
  examples/go.mod
  examples/go.sum
Labels: no changelog

#753 fix examples CI
  .github/workflows/examples.yml
  examples/basic/database_sql/series.go
Labels: no changelog
