Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-11, with the labels that each got.

#883 * Fixed inconsistent labels in `metrics`
  CHANGELOG.md
  metrics/sql.go
Labels: bug

#858 Allow to unwrap joined errors
  internal/xerrors/join.go
  internal/xerrors/join_test.go
Labels: no changelog

#884 Drop lazy init
  CHANGELOG.md
  connection.go
  driver.go
  internal/balancer/balancer.go
  internal/coordination/client.go
  internal/discovery/discovery.go
  internal/ratelimiter/client.go
  internal/scheme/client.go
  internal/scripting/client.go
  internal/table/client.go
  internal/table/client_test.go
  internal/table/session_test.go
  internal/topic/topicclientinternal/client.go
  internal/xerrors/join_test.go
  retry/retry.go
  trace/table.go
  trace/table_gtrace.go
Labels: refactoring

#885 fix CAS
  internal/conn/conn.go
Labels: no changelog

#886 move retry call detect into xcontext package
  internal/table/retry.go
  internal/xcontext/retry_call.go
  retry/retry.go
  retry/sql.go
  trace/retry.go
Labels: no changelog, refactoring

#887 Refactoring for better tracing
  CHANGELOG.md
  driver.go
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
  internal/conn/conn.go
  internal/conn/pool.go
  internal/discovery/discovery.go
  internal/meta/meta.go
  internal/mock/conn.go
  internal/repeater/repeater.go
  internal/repeater/repeater_test.go
  internal/scheme/client.go
  internal/scripting/client.go
  internal/stack/function_id.go
  internal/stack/record.go
  internal/table/client.go
  internal/table/retry.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/xresolver/xresolver.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  log/sql.go
  retry/retry.go
  retry/sql.go
  trace/call.go
  trace/discovery.go
  trace/discovery_gtrace.go
  trace/driver.go
  trace/driver_gtrace.go
  trace/retry.go
  trace/retry_gtrace.go
  trace/scheme.go
  trace/scheme_gtrace.go
  trace/scripting.go
  trace/scripting_gtrace.go
  trace/sql.go
  trace/sql_gtrace.go
  trace/table.go
  trace/table_gtrace.go
  with_test.go
Labels: refactoring

#889 Added function id into database/sql traces (start info's) + Fix of breaking changes
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  trace/sql.go
  trace/sql_gtrace.go
Labels: no changelog, refactoring

#890 balancer config name
  balancers/balancers.go
  balancers/balancers_test.go
  balancers/config.go
  balancers/config_test.go
  internal/balancer/balancer.go
  internal/balancer/config/routerconfig.go
  internal/balancer/connections_state.go
  internal/balancer/connections_state_test.go
  trace/driver.go
  trace/driver_gtrace.go
Labels: no changelog, refactoring

#892 added `Added` and `Dropped` fields into balancer update done info
  internal/balancer/balancer.go
  internal/balancer/balancer_test.go
  internal/balancer/local_dc_test.go
  log/driver.go
  trace/driver.go
  trace/driver_gtrace.go
Labels: bug, no changelog, refactoring, debug

#891 refactoring of xsql
  internal/xsql/conn.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  log/sql.go
  trace/sql.go
  trace/sql_gtrace.go
Labels: refactoring

#894 stack.FunctionID fix for codegen in the future
  driver.go
  internal/balancer/balancer.go
  internal/conn/conn.go
  internal/conn/pool.go
  internal/discovery/discovery.go
  internal/meta/meta.go
  internal/repeater/repeater.go
  internal/scheme/client.go
  internal/scripting/client.go
  internal/stack/function_id.go
  internal/stack/record.go
  internal/table/client.go
  internal/table/retry.go
  internal/table/retry_test.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/xresolver/xresolver.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  retry/retry.go
  retry/sql.go
  trace/driver.go
  trace/driver_gtrace.go
  with.go
Labels: refactoring

#900 allow to fail SLO tests
  .github/workflows/slo.yml
Labels: no changelog
