Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-10, with the labels that each got.

#844 * Refactored default logger format
  CHANGELOG.md
  log/join.go
  log/join_test.go
  log/logger.go
  log/logger_test.go
Labels: refactoring

#845 * Added repeater event type to wake-up func context
  CHANGELOG.md
  internal/repeater/repeater.go
Labels: refactoring

#846 * Fixed redundant trace call for finished `database/sql` transactions
  CHANGELOG.md
  internal/xsql/conn.go
  internal/xsql/errors.go
  internal/xsql/tx.go
Labels: bug, refactoring

#842 * Added package `metrics` with SDK metrics
  CHANGELOG.md
  metrics/README.md
  metrics/config.go
  metrics/coordination.go
  metrics/counter.go
  metrics/discovery.go
  metrics/driver.go
  metrics/error.go
  metrics/example_test.go
  metrics/gauge.go
  metrics/histogram.go
  metrics/node_id.go
  metrics/ratelimiter.go
  metrics/registry.go
  metrics/retry.go
  metrics/scheme.go
  metrics/scripting.go
  metrics/sql.go
  metrics/table.go
  metrics/timer.go
  metrics/traces.go
  table/table.go
  tests/integration/database_sql_test.go
  tests/integration/metrics_registry_go1.18_test.go
  tests/integration/metrics_registry_test.go
  tests/integration/table_test.go
  trace/table.go
Labels: bug, enhancement, refactoring, tests

#848 * Added receiving first result set on construct `internal/table/scanner.NewStream()`
  CHANGELOG.md
  internal/scripting/client.go
  internal/table/scanner/result.go
  internal/table/scanner/result_test.go
  internal/table/session.go
  internal/xerrors/join.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_scan_error_test.go
Labels: bug, no changelog

#850 refactoring of retry options for `retry.Retry`, `retry.Do`, `retry.DoTx`, `table.Do`, `table.DoTx`
  CHANGELOG.md
  SQL.md
  example_test.go
  examples/basic/database_sql/series.go
  internal/table/client.go
  internal/table/retry.go
  internal/table/retry_test.go
  metrics/table.go
  retry/retry.go
  retry/sql.go
  retry/sql_test.go
  table/table.go
  tests/integration/database_sql_containers_test.go
  tests/integration/database_sql_get_column_type_test.go
  tests/integration/database_sql_get_columns_test.go
  tests/integration/database_sql_get_index_columns_test.go
  tests/integration/database_sql_get_indexes_test.go
  tests/integration/database_sql_get_primary_keys_test.go
  tests/integration/database_sql_get_tables_test.go
  tests/integration/database_sql_is_column_exists_test.go
  tests/integration/database_sql_is_primary_key_test.go
  tests/integration/database_sql_is_table_exists_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/database_sql_test.go
  tests/integration/table_truncated_err_test.go
  tests/slo/database/sql/storage.go
  tests/slo/gorm/storage.go
  tests/slo/xorm/storage.go
  trace/table.go
  trace/table_gtrace.go
Labels: refactoring

#852 Removed `backoff.Backoff.Wait` interface method for exclude resource leak with bug-provoked usage of `time.After`
  CHANGELOG.md
  internal/backoff/backoff.go
  internal/repeater/repeater.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/wait/wait.go
  internal/xsql/errors.go
Labels: bug, refactoring

#849 refactoring of integration tests with basic example
  internal/balancer/connections_state_test.go
  tests/integration/basic_example_data.go
  tests/integration/basic_example_database_sql_bindings_test.go
  tests/integration/basic_example_database_sql_test.go
  tests/integration/basic_example_native_test.go
  tests/integration/database_sql_test.go
  tests/integration/table_test.go
Labels: no changelog, refactoring, CI, no slo

#857 fix unwrap raw values in wide results
  CHANGELOG.md
  internal/table/scanner/scanner.go
  tests/integration/table_regress_test.go
Labels: bug

#859 * Refactored credentials options (from funcs to interfaces and types)
  CHANGELOG.md
  connection.go
  credentials/credentials.go
  credentials/options.go
  internal/balancer/balancer.go
  internal/conn/middleware.go
  internal/credentials/access_token.go
  internal/credentials/anonymous.go
  internal/credentials/options.go
  internal/credentials/source_info.go
  internal/credentials/static.go
  internal/credentials/unauthenticated_error.go
  internal/credentials/unauthenticated_error_test.go
  tests/integration/database_sql_static_credentials_test.go
  tests/integration/static_credentials_test.go
Labels: refactoring

#861 Downgrade dependencies from `golang.org/x`
  CHANGELOG.md
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  internal/credentials/unauthenticated_error_test.go
  tests/slo/go.mod
  tests/slo/go.sum
Labels: bug, dependencies

#865 * Changed period for re-fresh static credentials token from `1/2` to …
  CHANGELOG.md
  internal/credentials/static.go
Labels: refactoring

#866 * Added `internal/credentials.IsAccessError(err)` helper for check ac…
  CHANGELOG.md
  internal/balancer/balancer.go
  internal/credentials/access_error.go
  internal/credentials/access_error_test.go
  internal/credentials/unauthenticated_error.go
Labels: refactoring

#867 rename of Driver variable name
  connection.go
  with.go
Labels: refactoring

#869 refactored `internal/stack`
  internal/stack/record.go
  internal/stack/record_test.go
  internal/table/retry.go
Labels: no changelog, refactoring

#870 added `metrics.TestErrorBrief` + allowed to create `xerrors.TransportError()` from grpc status error
  metrics/error.go
  metrics/error_brief.go
  metrics/error_brief_test.go
Labels: no changelog, tests

#873 fix TestErrorBrief
  metrics/error_brief_test.go
Labels: no changelog, refactoring

#874 * Moved `internal/allocator.Buffers` to package `internal/xstring`
  CHANGELOG.md
  internal/allocator/allocator.go
  internal/allocator/allocator_go1.18.go
  internal/bind/auto_declare.go
  internal/bind/bind.go
  internal/bind/numeric_args.go
  internal/bind/positional_args.go
  internal/bind/table_path_prefix.go
  internal/credentials/access_error.go
  internal/credentials/access_token.go
  internal/credentials/anonymous.go
  internal/credentials/static.go
  internal/stack/record.go
  internal/table/scanner/scanner.go
  internal/value/type.go
  internal/value/value.go
  internal/xerrors/issues.go
  internal/xerrors/join.go
  internal/xerrors/operation.go
  internal/xstring/buffer.go
  internal/xstring/buffer_test.go
  log/field.go
  log/logger.go
  metrics/error_brief.go
  table/table.go
Labels: refactoring

#868 * Added `ydb.WithTraceRetry` option
  CHANGELOG.md
  config/config.go
  connection.go
  internal/balancer/balancer.go
  internal/config/config.go
  internal/coordination/client.go
  internal/ratelimiter/client.go
  internal/scheme/client.go
  internal/scripting/client.go
  internal/table/client.go
  internal/table/retry.go
  internal/topic/topicclientinternal/client.go
  internal/xsql/connector.go
  metrics/retry.go
  metrics/traces.go
  options.go
  retry/retry.go
  retry/retry_test.go
  retry/sql.go
  retry/sql_test.go
  sql.go
  tests/integration/with_trace_retry_test.go
  tests/slo/database/sql/storage.go
  tests/slo/gorm/storage.go
  tests/slo/xorm/storage.go
Labels: enhancement

#875 * Renamed `{retry,table}.WithID` option to `{retry,table}.WithLabel`
  CHANGELOG.md
  internal/table/retry.go
  log/retry.go
  log/table.go
  metrics/table.go
  retry/retry.go
  retry/sql.go
  table/table.go
  tests/integration/with_trace_retry_test.go
  trace/retry.go
  trace/retry_gtrace.go
  trace/table.go
  trace/table_gtrace.go
Labels: refactoring

#876 xsql fixes
  internal/xsql/badconn/badconn_go1.18_test.go
  internal/xsql/conn.go
  internal/xsql/errors.go
  internal/xsql/isolation/isolation.go
  internal/xsql/rows.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
Labels: refactoring

#877 fix x-ydb-trace-id
  internal/conn/conn.go
  internal/conn/trace_id.go
  internal/conn/trace_id_test.go
  internal/meta/context.go
  internal/meta/trace_id.go
  internal/meta/trace_id_test.go
Labels: no changelog, refactoring

#878 * Added `table.SnapshotReadOnlyTxControl()` helper for get transactio…
  CHANGELOG.md
  internal/xsql/context.go
  table/table.go
  tests/integration/database_sql_with_tx_control_test.go
Labels: enhancement, tests

#879 added repeater init event
  internal/balancer/balancer.go
  internal/repeater/repeater.go
Labels: no changelog, refactoring

#880 finalErr in retry
  retry/retry.go
  retry/sql.go
Labels: no changelog, refactoring

#860 * Refactored traces and metrics
  CHANGELOG.md
  metrics/driver.go
  metrics/retry.go
  metrics/sql.go
  metrics/table.go
  retry/retry.go
Labels: bug, enhancement, refactoring, metrics
