Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-04, with the labels that each got.

#674 * Changed behaviour of retryer on transport errors `cancelled` and `d…
  CHANGELOG.md
  internal/xerrors/transport.go
  retry/errors_data_test.go
  retry/retry.go
  retry/retry_test.go
Labels: bug

#677 * Added `ydb.{WithTablePathPrefix,WithAutoDeclare,WithPositionalArgs,…
  CHANGELOG.md
  SQL.md
  example_test.go
  internal/query/bind.go
  internal/query/bind_auto_declare.go
  internal/query/bind_helpers.go
  internal/query/bind_helpers_test.go
  internal/query/bind_numeric_args.go
  internal/query/bind_params.go
  internal/query/bind_params_test.go
  internal/query/bind_positional_args.go
  internal/query/bind_table_path_prefix.go
  internal/query/errors.go
  internal/query/params.go
  internal/query/params_test.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/context.go
  internal/xsql/declare.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  query_bind_test.go
  sql.go
  sugar/params.go
  sugar/params_go1.18.go
  table/query/bind.go
  table/query/bind_test.go
  table/types/compare_test.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/helpers_test.go
  tests/integration/table_value_to_yql_literal_test.go
  testutil/compare_test.go
  testutil/driver.go
  testutil/driver_test.go
  testutil/query_bind.go
  trace/details.go
  trace/details_test.go
Labels: enhancement

#678 gorelease command
  .github/workflows/breaking.yml
Labels: no changelog

#680 gorelease
  .github/workflows/breaking.yml
Labels: no changelog

#679 Slo workflow update
  .github/workflows/slo.yml
  tests/slo/Dockerfile
  tests/slo/database/sql/main.go
Labels: no changelog

#681 feat: add language_id support for slo workflow
  .github/workflows/slo.yml
Labels: no changelog

#682 sql lexer for queries with positional and numeric args
  internal/query/bind_helpers.go
  internal/query/bind_helpers_test.go
  internal/query/bind_numeric_args.go
  internal/query/bind_numeric_args_test.go
  internal/query/bind_params.go
  internal/query/bind_params_test.go
  internal/query/bind_positional_args.go
  internal/query/bind_positional_args_test.go
  internal/query/params.go
  internal/query/params_test.go
  internal/query/sql_lexer.go
  query_bind_test.go
Labels: no changelog

#684 refactoring
  internal/bind/auto_declare.go
  internal/bind/bind.go
  internal/bind/errors.go
  internal/bind/numeric_args.go
  internal/bind/numeric_args_test.go
  internal/bind/params.go
  internal/bind/params_test.go
  internal/bind/positional_args.go
  internal/bind/positional_args_test.go
  internal/bind/sql_lexer.go
  internal/bind/table_path_prefix.go
  internal/xsql/connector.go
  internal/xsql/context.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  query_bind_test.go
  sql.go
  sugar/params.go
  sugar/params_go1.18.go
  sugar/params_go1.18_test.go
  testutil/query_bind.go
Labels: no changelog

#685 remove testutil/timeutil
  CHANGELOG.md
  go.mod
  go.sum
  internal/table/client.go
  internal/table/client_test.go
  internal/table/config/config.go
  internal/table/scanner/perfomance_test.go
  testutil/timeutil/hook.go
  testutil/timeutil/timetest/timetest.go
  testutil/timeutil/timeutil.go
Labels: no changelog

#686 fakeTx
  CHANGELOG.md
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  sql.go
Labels: enhancement

#687 sort bindings
  internal/bind/auto_declare.go
  internal/bind/bind.go
  internal/bind/bind_test.go
  internal/bind/numeric_args.go
  internal/bind/positional_args.go
  internal/bind/table_path_prefix.go
  internal/xsql/connector.go
  internal/xsql/context.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  sql.go
  testutil/query_bind.go
Labels: bug, enhancement, no changelog

#689 ignore ?? on positional args binder
  internal/bind/positional_args.go
  query_bind_test.go
Labels: bug

#690 drop ydb.WithCompression bc import of encoding/gzip changed global re…
  CHANGELOG.md
  example_test.go
  options.go
  tests/integration/table_bulk_upsert_example_test.go
Labels: bug

#695 database/sql static credentials test
  tests/integration/database_sql_static_credentials_test.go
Labels: tests

#671 SLO workload
  .github/scripts/check-work-copy-equals-to-committed.sh
  .github/scripts/format-all-go-code.sh
  .github/scripts/format-go-code.sh
  .github/scripts/is_autogenerated_file.sh
  .github/workflows/lint.yml
  .github/workflows/slo.yml
  .golangci.yml
  tests/slo/Dockerfile
  tests/slo/README.md
  tests/slo/go.mod
  tests/slo/go.sum
  tests/slo/internal/config/config.go
  tests/slo/internal/config/help.go
  tests/slo/internal/config/modes.go
  tests/slo/internal/generator/generator.go
  tests/slo/internal/generator/row.go
  tests/slo/internal/metrics/metrics.go
  tests/slo/internal/metrics/span.go
  tests/slo/internal/workers/metrics.go
  tests/slo/internal/workers/read.go
  tests/slo/internal/workers/workers.go
  tests/slo/internal/workers/write.go
  tests/slo/native/README.md
  tests/slo/native/main.go
  tests/slo/native/storage.go
Labels: no changelog

#699 fix: sugar.RemoveRecursive do nothing if path is database root
  sugar/path.go
Labels: no changelog

#700 fix: slo workload native
  tests/slo/internal/config/config.go
Labels: bug, no changelog

#701 fix: logging nil errors in slo native workers
  tests/slo/internal/workers/read.go
  tests/slo/internal/workers/write.go
Labels: bug, no changelog, tests

#696 removed WithBlock() from defaults
  CHANGELOG.md
  config/defaults.go
Labels: bug

#706 fix breakinig action
  .github/workflows/breaking.yml
  .gitignore
Labels: bug

#709 fix bug with no put session before second discovery
  CHANGELOG.md
  connection.go
  internal/balancer/balancer.go
  internal/table/client.go
  internal/table/client_test.go
  internal/table/session_test.go
Labels: bug

#710 fix bugfix
  connection.go
  internal/table/client.go
  internal/table/client_test.go
  internal/table/session_test.go
Labels: bug

#702 SLO workload database/sql
  .github/workflows/slo.yml
  tests/slo/database/sql/README.md
  tests/slo/database/sql/main.go
  tests/slo/database/sql/storage.go
  tests/slo/internal/generator/generator.go
  tests/slo/internal/generator/row.go
  tests/slo/native/storage.go
Labels: no changelog, CI, tests

#715 dependencies: update gorm-driver
  examples/go.mod
  examples/go.sum
Labels: no changelog, dependencies
