Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-01, with the labels that each got.

#509 * Added `trace.Details.Details()` method for use external detailer
  CHANGELOG.md
  trace/details.go
Labels: enhancement

#515 * Added `ydb.WithDisableServerBalancer()` database/sql connector option
  CHANGELOG.md
  internal/xsql/connector.go
  sql.go
Labels: enhancement

#520 hide PublicErrCommitSessionToExpiredSession for async commit mode
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
Labels: no changelog

#522 * Fixed wrapping error in `internal/balancer/Balancer.wrapCall()`
  CHANGELOG.md
  internal/balancer/balancer.go
  internal/conn/conn.go
  internal/conn/context.go
Labels: bug

#516 * Fixed closing of database/sql connection (aka `YDB` session)
  CHANGELOG.md
  internal/table/session.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/errors.go
  internal/xsql/rows.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/unwrap.go
  internal/xsql/unwrap_go1.18.go
  options.go
  table/table_e2e_test.go
Labels: bug, enhancement

#525 Added check for nil option to all opts range loops
  CHANGELOG.md
  balancers/config.go
  config/config.go
  connection.go
  credentials/credentials.go
  internal/backoff/backoff.go
  internal/certificates/certificates.go
  internal/cmd/gtrace/writer.go
  internal/conn/conn.go
  internal/coordination/config/config.go
  internal/discovery/config/config.go
  internal/endpoint/endpoint.go
  internal/logger/log.go
  internal/meta/meta.go
  internal/ratelimiter/config/config.go
  internal/ratelimiter/options/acquire.go
  internal/repeater/repeater.go
  internal/scheme/client.go
  internal/scheme/config/config.go
  internal/scheme/options_test.go
  internal/scripting/config/config.go
  internal/table/client.go
  internal/table/config/config.go
  internal/table/retry.go
  internal/table/scanner/result.go
  internal/table/scanner/result_test.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/topic/topicclientinternal/client.go
  internal/topic/topicreaderinternal/reader.go
  internal/xerrors/operation.go
  internal/xerrors/retryable.go
  internal/xerrors/stacktrace.go
  internal/xerrors/transport.go
  internal/xrand/xrand.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xtest/manytimes.go
  log/options.go
  options.go
  retry/retry.go
  retry/retryable_error.go
  retry/sql.go
  table/options/options.go
  table/table.go
  table/types/types.go
  table/types/value.go
  testutil/driver.go
  testutil/session.go
  trace/details.go
  trace/discovery_gtrace.go
  trace/driver_gtrace.go
  trace/retry_gtrace.go
  trace/scripting_gtrace.go
  trace/sql_gtrace.go
  trace/table_gtrace.go
  trace/topic_gtrace.go
Labels: bug, enhancement

#532 Add short stress test of topic reader-writer
  .github/workflows/tests.yml
  internal/xtest/waiters.go
  topic/client_e2e_test.go
  topic/topic_read_writer_e2e_test.go
  topic/topic_stress_test.go
Labels: no changelog

#492 Issue 487 reader stop after update token
  internal/topic/topicreaderinternal/stream_reader_impl.go
  topic/client_e2e_test.go
  topic/topic_read_writer_e2e_test.go
Labels: no changelog

#530 Drop `internal/xnet` + replace permanent connection into newest connection each discovery
  CHANGELOG.md
  config/config.go
  config/defaults.go
  connection.go
  discovery/discovery_e2e_test.go
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
  internal/discovery/discovery.go
  internal/xnet/xnet.go
Labels: enhancement, refactoring

#534 fix wait timeout for ci env
  topic/topic_stress_test.go
Labels: no changelog

#533 * Moved content of package `internal/ctxlabels` into `internal/xcontext` + implements GRPCStatus() method in transport errors
  CHANGELOG.md
  internal/conn/conn.go
  internal/conn/grpc_client_stream.go
  internal/grpcwrapper/rawtopic/rawtopicreader/rawtopicreader.go
  internal/grpcwrapper/rawtopic/rawtopicwriter/streamwriter.go
  internal/table/retry_test.go
  internal/topic/retriable_error_test.go
  internal/xcontext/local_dc.go
  internal/xerrors/stacktrace.go
  internal/xerrors/stacktrace_test.go
  internal/xerrors/transport.go
  internal/xerrors/transport_test.go
  internal/xerrors/ydb_test.go
  internal/xsql/badconn/badconn_go1.18_test.go
  retry/errors_data_test.go
Labels: enhancement

#536 * Fixed retry of cluster discovery on initialization
  CHANGELOG.md
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
Labels: enhancement, refactoring

#537 fix flack send initial size
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
Labels: no changelog

#540 * Fixed `sugar.IsTableExists` with recursive check directory exists
  CHANGELOG.md
  connection.go
  internal/scheme/client.go
  internal/scheme/config/config.go
  internal/scheme/helpers/check_exists.go
  internal/scheme/helpers/check_exists_test.go
  internal/scheme/helpers/table_exists.go
  sugar/check_exists.go
Labels: bug, enhancement

#541 moved all e2e tests to ./tests directory
  .github/workflows/tests.yml
  sql_e2e_test.go
  tests/README.md
  tests/connection_test.go
  tests/database_sql_regression_test.go
  tests/database_sql_test.go
  tests/discovery_test.go
  tests/monitoring_test.go
  tests/ratelimiter_test.go
  tests/scripting_test.go
  tests/static_credentials_test.go
  tests/table_regression_test.go
  tests/table_test.go
  tests/topic_cdc_reader_test.go
  tests/topic_client_test.go
  tests/topic_grpc_stopper_helper_test.go
  tests/topic_read_writer_test.go
  tests/topic_stress_test.go
Labels: no changelog, refactoring
