Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-02, with the labels that each got.

#547 Revert "corner cases for wait.Wait"
  internal/wait/wait.go
Labels: no changelog

#546 upgrade latest version to go 1.20
  .github/workflows/breaking.yml
  .github/workflows/check-codegen.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: no changelog

#548 xerrors.MultiErrorf + corner cases of wrap.Wrap
  CHANGELOG.md
  internal/table/client_test.go
  internal/table/retry.go
  internal/table/retry_test.go
  internal/wait/wait.go
  internal/xerrors/multi_errorf.go
  internal/xerrors/multi_errorf_test.go
  internal/xerrors/xerrors.go
  retry/retry.go
Labels: bug, refactoring

#550 fixed xerrors.MultiErrorf -> xerrors.Errorf
  CHANGELOG.md
  internal/xerrors/errorf.go
  internal/xerrors/errorf_test.go
  internal/xerrors/issues.go
  retry/retry.go
Labels: refactoring

#554 integration tests for secure and insecure connections
  .github/workflows/tests.yml
Labels: no changelog, CI

#555 update requirment actions
  .github/workflows/breaking.yml
  .github/workflows/changelog.yml
  .github/workflows/check-codegen.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: no changelog, CI

#563 fix pool initialization after config applying
  connection.go
Labels: bug, no changelog

#564 fixed grpc dial - make grpc dial options on real dial stage
  internal/conn/conn.go
Labels: no changelog, refactoring

#552 * Added `trace.Driver.{OnBalancerDialEntrypoint,OnBalancerClusterDiscoveryAttempt}` trace events
  CHANGELOG.md
  connection.go
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
  log/driver.go
  trace/driver.go
  trace/driver_gtrace.go
Labels: bug

#569 * Fixed compilation of package `internal/xresolver` with `google.gola…
  CHANGELOG.md
  internal/xresolver/xresolver.go
Labels: bug

#570 * Added wrapping of errors from unary and stream results
  CHANGELOG.md
  internal/table/scanner/result.go
  internal/xsql/conn.go
  internal/xsql/rows.go
  internal/xsql/tx.go
  tests/database_sql_regression_test.go
  tests/table_test.go
Labels: bug, refactoring, CI

#571 refactoring of exaamples
  connection_test.go
  example_test.go
Labels: no changelog, refactoring, CI

#572 refactored integration tests + add slo workloads paths
  .github/workflows/tests.yml
  tests/README.md
  tests/integration/README.md
  tests/integration/connection_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/database_sql_test.go
  tests/integration/discovery_test.go
  tests/integration/monitoring_test.go
  tests/integration/ratelimiter_test.go
  tests/integration/scripting_test.go
  tests/integration/static_credentials_test.go
  tests/integration/table_regression_test.go
  tests/integration/table_test.go
  tests/integration/topic_cdc_reader_test.go
  tests/integration/topic_client_test.go
  tests/integration/topic_grpc_stopper_helper_test.go
  tests/integration/topic_read_writer_test.go
  tests/integration/topic_stress_test.go
  tests/slo/database/sql/README.md
  tests/slo/native/README.md
Labels: no changelog, refactoring, CI

#574 fix TestRegressionKikimr17104
  tests/integration/database_sql_regression_test.go
Labels: bug, no changelog, refactoring, CI

#575 * Added exit from retryer if got grpc-error `Unauthenticated` on `dis…
  CHANGELOG.md
  internal/balancer/balancer.go
Labels: bug

#577 Added internal methods for optional type for casts some type to optional
  internal/value/type.go
  table/types/types.go
  table/types/types_test.go
Labels: no changelog, refactoring, CI

#474 zap-like structural logger
  internal/logs/traces/coordination.go
  internal/logs/traces/discovery.go
  internal/logs/traces/driver.go
  internal/logs/traces/fields.go
  internal/logs/traces/logger.go
  internal/logs/traces/options.go
  internal/logs/traces/ratelimiter.go
  internal/logs/traces/retry.go
  internal/logs/traces/scheme.go
  internal/logs/traces/scripting.go
  internal/logs/traces/secret.go
  internal/logs/traces/sql.go
  internal/logs/traces/table.go
  internal/logs/traces/topic.go
  internal/logs/traces/types.go
  log/adapter.go
  log/coordination.go
  log/discovery.go
  log/driver.go
  log/level.go
  log/options.go
  log/ratelimiter.go
  log/retry.go
  log/scheme.go
  log/scripting.go
  log/secret.go
  log/sql.go
  log/table.go
  log/topic.go
  logs/field.go
  logs/level.go
  logs/logger.go
Labels: enhancement, community

#581 Bind funcs from clickhouse-go repo
  internal/xsql/bind.go
  internal/xsql/bind_test.go
Labels: no changelog, refactoring

#589 fix flaky test TestWorkerConcurrentStartAndClose
  internal/background/worker_test.go
  internal/xtest/context.go
Labels: no changelog

#585 fixed grpcs connection in examples to grpc connection
  README.md
  SQL.md
  SQL_MIGRATION_v2_v3.md
  coordination/example_test.go
  discovery/example_test.go
  example_test.go
  meta/example_test.go
  ratelimiter/example_test.go
  scheme/example_test.go
  scripting/example_test.go
  table/example_test.go
  topic/README.md
Labels: documentation, no changelog

#590 Fix flacky TestReadersWritersStress
  internal/xtest/waiters.go
  tests/integration/topic_stress_test.go
Labels: no changelog

#591 Deprecated `trace.Driver.OnConnTake` event callback + Added `trace.Driver.OnConnDial` event callback
  CHANGELOG.md
  internal/conn/conn.go
  log/driver.go
  trace/driver.go
  trace/driver_gtrace.go
Labels: enhancement

#593 fixed integration tests and examples with dsn args
  example_test.go
  internal/xsql/conn.go
  internal/xsql/conn_test.go
  internal/xsql/dsn.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
Labels: no changelog

#595 fix integration tests
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/database_sql_test.go
Labels: no changelog

#600 * Fixed bug with no checking of operation result in `discovery` clien…
  CHANGELOG.md
  internal/conn/conn.go
  internal/discovery/discovery.go
  internal/operation/errors.go
Labels: bug, refactoring

#607 fixed sugar.{Make,Remove}Recursive + added integration test
  sugar/path.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_test.go
  tests/integration/sugar_make_remove_recursive_test.go
  tests/integration/table_test.go
Labels: bug, no changelog, tests

#599 * Changed result type in `ydb.Open()` from `ydb.Connection` interface type to `*ydb.Driver`
  CHANGELOG.md
  connection.go
  example_test.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/unwrap.go
  options.go
  sql.go
  sql_unwrap.go
  sql_unwrap_go1.18.go
  sugar/path.go
  tests/integration/connection_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/table_regression_test.go
  tests/integration/table_test.go
  tests/integration/topic_cdc_reader_test.go
  tests/integration/topic_client_test.go
  tests/integration/topic_read_writer_test.go
  tests/integration/topic_stress_test.go
  topic/topicoptions/topicoptions_reader_example_test.go
  topic/topicoptions/topicoptions_writer_example_test.go
  with.go
  with_test.go
Labels: refactoring
