Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-03, with the labels that each got.

#608 drop examples/bulk_upsert + create integration test of bulk_upsert
  examples/bulk_upsert/README.md
  examples/bulk_upsert/example.go
  examples/bulk_upsert/main.go
  examples/go.mod
  internal/logger/log.go
  internal/xtest/context.go
  internal/xtest/logger.go
  tests/integration/connection_test.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/database_sql_test.go
  tests/integration/discovery_test.go
  tests/integration/monitoring_test.go
  tests/integration/ratelimiter_test.go
  tests/integration/scripting_test.go
  tests/integration/static_credentials_test.go
  tests/integration/sugar_make_remove_recursive_test.go
  tests/integration/table_bulk_upsert_test.go
  tests/integration/table_create_table_description_test.go
  tests/integration/table_interval_from_duration_test.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/table_null_type_test.go
  tests/integration/table_scan_error_test.go
  tests/integration/table_test.go
  tests/integration/table_tx_lazy_test.go
  tests/integration/table_unexpected_null_while_parse_nil_json_document_value_test.go
  tests/integration/topic_cdc_reader_test.go
  tests/integration/topic_client_test.go
  tests/integration/topic_partitions_balanced_test.go
  tests/integration/topic_read_messages_test.go
  tests/integration/topic_read_writer_test.go
  tests/integration/topic_stress_test.go
Labels: no changelog, refactoring

#612 * Changed default output stream of internal logger to `io.Stderr`
  CHANGELOG.md
  internal/logger/log.go
  internal/logger/options.go
  logger_options.go
  tests/integration/connection_test.go
  tests/integration/discovery_test.go
  tests/integration/ratelimiter_test.go
  tests/integration/scripting_test.go
  tests/integration/table_bulk_upsert_test.go
  tests/integration/table_create_table_description_test.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/table_test.go
  tests/integration/topic_read_writer_test.go
Labels: enhancement

#609 bulk_upsert example with fixtures
  go.mod
  go.sum
  tests/integration/helpers_test.go
  tests/integration/table_bulk_upsert_example_test.go
  tests/integration/table_bulk_upsert_test.go
Labels: no changelog, refactoring

#611 t.Parallel()
  connection_test.go
  tests/integration/connection_test.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/database_sql_test.go
  tests/integration/discovery_test.go
  tests/integration/monitoring_test.go
  tests/integration/scripting_test.go
  tests/integration/static_credentials_test.go
  tests/integration/sugar_make_remove_recursive_test.go
  tests/integration/table_create_table_description_test.go
  tests/integration/table_interval_from_duration_test.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/table_null_type_test.go
  tests/integration/table_scan_error_test.go
  tests/integration/table_test.go
  tests/integration/table_tx_lazy_test.go
  tests/integration/table_unexpected_null_while_parse_nil_json_document_value_test.go
  tests/integration/topic_cdc_reader_test.go
  tests/integration/topic_client_test.go
  tests/integration/topic_partitions_balanced_test.go
  tests/integration/topic_read_messages_test.go
  tests/integration/topic_read_writer_test.go
  tests/integration/topic_stress_test.go
Labels: no changelog

#616 added integration test for different tx-controls
  tests/integration/database_sql_regression_test.go
  tests/integration/table_tx_control_test.go
Labels: no changelog

#618 cache compiled dependencies for improve compile speed, especially for windows
  .github/workflows/tests.yml
Labels: no changelog

#619 Replaced the balancer connection to discovery service from short-live…
  CHANGELOG.md
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
  log/driver.go
  trace/driver.go
Labels: bug

#615 simplify sql numeric integration test
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/helpers_test.go
Labels: no changelog

#621 * Replaced the balancer connection to discovery service from short-li…
  CHANGELOG.md
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
  internal/conn/conn.go
  log/driver.go
  trace/driver.go
  trace/driver_gtrace.go
Labels: bug

#623 Longer time for wait progress
  tests/integration/topic_stress_test.go
Labels: no changelog

#624 enabled by default bindings in `database/sql`
  CHANGELOG.md
  bind/bind.go
  internal/xsql/bind/bind.go
  internal/xsql/bind/bind_test.go
  internal/xsql/bind/bindings.go
  internal/xsql/bind/declare.go
  internal/xsql/bind/pragma.go
  internal/xsql/bind/wrap.go
  internal/xsql/bind/wrap.yql
  internal/xsql/conn.go
  internal/xsql/conn_test.go
  internal/xsql/connector.go
  internal/xsql/context.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  internal/xsql/tx.go
  sql.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_test.go
  tests/integration/helpers_test.go
Labels: refactoring

#634 Remove recursive topic
  CHANGELOG.md
  sugar/path.go
  tests/integration/database_sql_test.go
  tests/integration/sugar_make_remove_recursive_test.go
  tests/integration/table_test.go
Labels: bug

#639 * Fixed default state of `internal/xerrors.retryableError`: it inheri…
  CHANGELOG.md
  internal/conn/conn.go
  internal/xerrors/retryable.go
Labels: bug

#640 CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#644 fix naming / revert modificationMark field about dirty or can retry
  internal/conn/conn.go
Labels: no changelog

#645 Databasesql test
  CHANGELOG.md
  internal/scheme/client.go
  internal/scheme/helpers/check_exists.go
  internal/xsql/conn.go
  internal/xsql/conn_test.go
  internal/xsql/connector.go
  internal/xsql/tx.go
  scheme/scheme.go
  sql.go
  tests/integration/database_sql_scheme_test.go
Labels: bug

#651 fix compile examples
  examples/go.mod
  examples/go.sum
Labels: no changelog

#646 * WithBlock()
  CHANGELOG.md
  config/defaults.go
  internal/conn/conn.go
  internal/conn/grpc_client_stream.go
  internal/xerrors/transport.go
  internal/xsql/bind/args_type.go
  internal/xsql/bind/bind.go
  internal/xsql/mode.go
  tests/integration/database_sql_regression_test.go
Labels: bug

#656 fix bindings
  .github/workflows/tests.yml
  CHANGELOG.md
  internal/xsql/bind/args_type.go
  internal/xsql/bind/bind.go
  internal/xsql/bind/bind_test.go
  internal/xsql/bind/errors.go
  internal/xsql/bind/pragma.go
  internal/xsql/bind/wrap.go
  internal/xsql/bind/wrap.yql
  internal/xsql/conn.go
  internal/xsql/conn_test.go
  internal/xsql/connector.go
  internal/xsql/context.go
  internal/xsql/convert/convert.go
  internal/xsql/convert/convert_test.go
  internal/xsql/declare.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  internal/xsql/tx.go
  sql.go
  sugar/params_go1.18.go
  table/table.go
  table/table_test.go
  table/types/value.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/helpers_test.go
Labels: database/sql

#658 * Added `ydb.MustOpen` and `ydb.MustConnector` helpers
  CHANGELOG.md
  SQL.md
  connection.go
  example_test.go
  internal/xsql/bind/bind.go
  internal/xsql/bind/bind_test.go
  internal/xsql/bind/helpers.go
  internal/xsql/bind/helpers_test.go
  sql.go
Labels: documentation, database/sql

#659 switch ydb docker image from 22-5 to 23-1
  .github/workflows/tests.yml
Labels: no changelog

#660 changed fixed ydb version to matrix
  .github/workflows/tests.yml
Labels: no changelog

#661 * Added package `table.query` with bindings
  .github/workflows/lint.yml
  CHANGELOG.md
  SQL.md
  example_test.go
  internal/cmd/gtrace/writer.go
  internal/topic/topicreaderinternal/batched_stream_reader_interface.go
  internal/topic/topicreaderinternal/message_content_pool.go
  internal/topic/topicreaderinternal/reader.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicwriterinternal/writer.go
  internal/topic/topicwriterinternal/writer_stream_interface.go
  internal/xsql/bind/bind.go
  internal/xsql/bind/bind_test.go
  internal/xsql/bind/helpers.go
  internal/xsql/bind/helpers_test.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/convert/convert.go
  internal/xsql/convert/convert_test.go
  internal/xsql/dsn.go
  internal/xsql/dsn_test.go
  sql.go
  sugar/certificates.go
  sugar/params_go1.18.go
  table/query/bind.go
  table/query/bind_test.go
  table/table.go
  tests/integration/database_sql_numeric_args_test.go
  tests/integration/database_sql_positional_args_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/helpers_test.go
  topic/example_test.go
Labels: database/sql

#665 * Added `ydb.WithCompression()` option
  CHANGELOG.md
  options.go
  tests/integration/helpers_test.go
  tests/integration/table_bulk_upsert_example_test.go
Labels: enhancement

#667 refactored examples
  examples/go.mod
  examples/serverless/healthcheck/README.md
  examples/serverless/url_shortener/README.md
Labels: refactoring

#670 Empty slo config
  .github/workflows/slo.yml
  tests/slo/Dockerfile
  tests/slo/go.mod
  tests/slo/native/main.go
Labels: no changelog

#672 * Fixed bug with parsing of `TzTimestamp` without microseconds
  CHANGELOG.md
  internal/value/time.go
  internal/value/time_test.go
  tests/integration/table_tz_timestamp_test.go
Labels: bug

#675 * Fixed bug with put session from unknown node
  CHANGELOG.md
  internal/table/client.go
  internal/table/client_test.go
  internal/table/errors.go
  testutil/session.go
Labels: bug

#676 * Added address of node to operation error description as optional
  CHANGELOG.md
  internal/conn/conn.go
  internal/conn/grpc_client_stream.go
  internal/credentials/static.go
  internal/discovery/discovery.go
  internal/xerrors/issues.go
  internal/xerrors/operation.go
  internal/xerrors/operation_test.go
Labels: refactoring
