Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-09, with the labels that each got.

#812 fix reflect.{String,Slice}Header in go1.21
  CHANGELOG.md
  internal/xstring/convert.go
  internal/xstring/convert_go1.21.go
Labels: enhancement

#816 replace all atomic operations for atomic variables
  internal/background/worker_test.go
  internal/conn/conn.go
  internal/table/client_test.go
  internal/table/scanner/result.go
  internal/table/session.go
  internal/table/transaction.go
  internal/topic/topicreaderinternal/batcher_test.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/partition_session.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicwriterinternal/queue_test.go
  internal/xatomic/type.go
  internal/xatomic/type_go1.19.go
  internal/xsql/conn.go
  internal/xsync/event_broadcast_test.go
  tests/integration/database_sql_test.go
  tests/integration/table_test.go
  tests/integration/topic_partitions_balanced_test.go
  tests/integration/topic_stress_test.go
  topic/topicreader/reader.go
  with.go
Labels: no changelog, no slo

#815 Add test about free buffer after stop partition
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
Labels: no changelog, no slo

#818 fix green status
  .golangci.yml
  examples/go.mod
  go.mod
  internal/background/worker_test.go
  internal/backoff/backoff.go
  internal/backoff/backoff_test.go
  internal/balancer/connections_state.go
  internal/conn/conn.go
  internal/table/client_test.go
  internal/table/scanner/result.go
  internal/table/session.go
  internal/table/transaction.go
  internal/topic/topicreaderinternal/batcher_test.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/partition_session.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicwriterinternal/encoders_test.go
  internal/topic/topicwriterinternal/queue_test.go
  internal/xatomic/type.go
  internal/xatomic/type_go1.19.go
  internal/xrand/xrand.go
  internal/xsql/conn.go
  internal/xstring/convert.go
  internal/xstring/convert_go1.20.go
  internal/xsync/event_broadcast_test.go
  tests/integration/database_sql_test.go
  tests/integration/table_test.go
  tests/integration/topic_partitions_balanced_test.go
  tests/integration/topic_stress_test.go
  tests/slo/go.mod
  topic/topicreader/reader.go
  with.go
Labels: no changelog, refactoring

#819 replace all atomic operations for atomic variables
  .github/workflows/tests.yml
  internal/background/worker_test.go
  internal/conn/conn.go
  internal/table/client_test.go
  internal/table/scanner/result.go
  internal/table/session.go
  internal/table/transaction.go
  internal/topic/topicreaderinternal/batcher_test.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/partition_session.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicwriterinternal/queue_test.go
  internal/xatomic/type.go
  internal/xatomic/type_go1.19.go
  internal/xsql/conn.go
  internal/xsync/event_broadcast_test.go
  tests/integration/database_sql_test.go
  tests/integration/table_test.go
  tests/integration/topic_partitions_balanced_test.go
  tests/integration/topic_stress_test.go
  topic/topicreader/reader.go
  with.go
Labels: no changelog

#817 fix comments
  internal/table/config/config.go
  options.go
Labels: documentation, no changelog

#822 upgrade test
  tests/integration/database_sql_test.go
Labels: no changelog, CI, database/sql, tests

#823 fix error message
  internal/conn/conn.go
  internal/conn/error.go
  internal/conn/error_test.go
  internal/conn/grpc_client_stream.go
Labels: no changelog, no slo

#825 * Added `table.Session.CopyTables` method
  CHANGELOG.md
  internal/table/errors.go
  internal/table/session.go
  internal/table/session_test.go
  table/example_test.go
  table/options/options.go
  table/table.go
  tests/integration/table_copy_tables_test.go
Labels: enhancement

#827 23.3 integration tests
  .github/workflows/tests.yml
  tests/integration/database_sql_static_credentials_test.go
  tests/integration/kv_test.go
  tests/integration/static_credentials_test.go
Labels: no changelog, CI

#832 * Supported placeholder "_" for ignored column names in `database/sql…
  CHANGELOG.md
  internal/xsql/rows.go
Labels: database/sql

#831 * Merged `internal/xsql/conn.{GetTables,GetAllTables}` methods for `DRY`
  CHANGELOG.md
  internal/xsql/conn.go
  internal/xsql/conn_test.go
  internal/xsql/connector.go
  tests/integration/database_sql_get_all_tables_test.go
  tests/integration/database_sql_get_tables_test.go
  tests/integration/database_sql_scheme_test.go
Labels: refactoring

#833 * Removed support of placeholder "_" for ignoring columns in `databas…
  CHANGELOG.md
  internal/xsql/rows.go
Labels: bug

#803 added WaitInit to Writer and Reader
  CHANGELOG.md
  internal/topic/topicreaderinternal/batched_stream_reader_interface.go
  internal/topic/topicreaderinternal/batched_stream_reader_mock_test.go
  internal/topic/topicreaderinternal/reader.go
  internal/topic/topicreaderinternal/reader_test.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/topic/topicreaderinternal/stream_reconnector_test.go
  internal/topic/topicwriterinternal/writer.go
  internal/topic/topicwriterinternal/writer_reconnector.go
  internal/topic/topicwriterinternal/writer_reconnector_test.go
  internal/topic/topicwriterinternal/writer_stream_interface.go
  internal/topic/topicwriterinternal/writer_stream_interface_mock_test.go
  internal/topic/topicwriterinternal/writer_test.go
  topic/topicreader/reader.go
  topic/topicwriter/topicwriter.go
Labels: enhancement, topic, no slo

#836 remove a lot of expirements comments.
  CHANGELOG.md
  examples/topic/topicreader/topicreader_advanced.go
  examples/topic/topicreader/topicreader_show.go
  internal/grpcwrapper/rawtopic/rawtopiccommon/codec.go
  internal/topic/topicclientinternal/client.go
  internal/topic/topicreaderinternal/batch.go
  internal/topic/topicreaderinternal/commit_range.go
  internal/topic/topicreaderinternal/committer.go
  internal/topic/topicreaderinternal/decoders.go
  internal/topic/topicreaderinternal/message.go
  internal/topic/topicreaderinternal/public_callbacks.go
  internal/topic/topicreaderinternal/reader.go
  topic/client.go
  topic/topicoptions/topicoptions_alter.go
  topic/topicoptions/topicoptions_create.go
  topic/topicoptions/topicoptions_describe.go
  topic/topicoptions/topicoptions_drop.go
  topic/topicoptions/topicoptions_reader.go
  topic/topicoptions/topicoptions_writer.go
  topic/topicreader/batch_options.go
  topic/topicreader/errors.go
  topic/topicreader/reader.go
  topic/topicsugar/topicreader.go
  topic/topictypes/topictypes.go
  topic/topicwriter/topicwriter.go
  trace/topic.go
Labels: no slo

#837 added TestNoEffectsIfForgetCommitTx
  internal/xsql/conn.go
  internal/xsql/errors.go
  tests/integration/database_sql_regression_test.go
  tests/integration/tx_test.go
Labels: bug, invalid, question, no changelog, database/sql, tests, no slo

#835 added cross join test + upgraded test helpers
  tests/integration/helpers_test.go
  tests/integration/table_cross_join_test.go
Labels: tests
