Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-12, with the labels that each got.

#903 Change golangci to enable all
  .golangci.yml
  connection.go
  driver.go
  errors.go
  example_test.go
  options.go
  query_bind_test.go
  sql.go
  sql_unwrap.go
  sql_unwrap_go1.18.go
  with.go
  with_test.go
Labels: no changelog, CI

#909 revert linter settings from https://github.com/ydb-platform/ydb-go-sd…
  .golangci.yml
Labels: no changelog

#910 internal message to public message - because the message is part of p…
  internal/topic/topicwriterinternal/encoders_test.go
  internal/topic/topicwriterinternal/message.go
  internal/topic/topicwriterinternal/writer.go
  internal/topic/topicwriterinternal/writer_reconnector.go
  internal/topic/topicwriterinternal/writer_reconnector_test.go
  internal/topic/topicwriterinternal/writer_stream_interface.go
  internal/topic/topicwriterinternal/writer_stream_interface_mock_test.go
  internal/topic/topicwriterinternal/writer_test.go
  topic/topicwriter/topicwriter.go
Labels: no changelog

#914 Driver string
  CHANGELOG.md
  config/defaults.go
  driver_string.go
  driver_string_test.go
  internal/credentials/access_error_test.go
  internal/credentials/access_token.go
  internal/credentials/anonymous.go
  internal/credentials/credentials_test.go
  internal/credentials/static.go
Labels: enhancement

#915 Revert golangci config
  .github/workflows/lint.yml
  .golangci.yml
Labels: refactoring, CI, linters

#978 asasalint enable
  .golangci.yml
  sugar/params_go1.18.go
  sugar/params_go1.18_test.go
Labels: no changelog, CI, linters

#979 sqlclosecheck enabled
  .golangci.yml
  retry/sql_test.go
Labels: no changelog, CI, no slo, linters

#986 bodyclose enabled
  .golangci.yml
  examples/serverless/healthcheck/service.go
Labels: no changelog, no slo, linters

#987 deadcode enabled
  .golangci.yml
  internal/cmd/gtrace/writer.go
Labels: no changelog, no slo, linters

#988 gosec enabled
  .golangci.yml
  balancers/config_test.go
Labels: no changelog, no slo, linters

#991 noctx enabled
  .golangci.yml
  examples/serverless/healthcheck/service.go
Labels: no changelog, no slo, linters

#990 nakedret enabled
  .golangci.yml
  examples/pagination/cities.go
Labels: no changelog, no slo, linters

#993 tagalign enabled
  .golangci.yml
  tests/slo/internal/generator/row.go
Labels: no changelog, no slo, linters

#994 tagliatelle enabled
  .golangci.yml
  examples/topic/topicreader/topicreader_simple.go
Labels: no changelog, no slo, linters

#992 promlinter enabled
  .golangci.yml
  examples/serverless/url_shortener/service.go
Labels: no changelog, no slo, linters

#995 varcheck enabled
  .golangci.yml
Labels: no changelog, no slo, linters

#989 gochecknoinits enabled
  .golangci.yml
  examples/auth/access_token_credentials/main.go
  examples/auth/anonymous_credentials/main.go
  examples/auth/metadata_credentials/main.go
  examples/auth/service_account_credentials/main.go
  examples/auth/static_credentials/main.go
  examples/ddl/main.go
  examples/decimal/main.go
  examples/pagination/main.go
  examples/read_table/main.go
  examples/serverless/healthcheck/main.go
  examples/serverless/url_shortener/main.go
  examples/ttl/main.go
  examples/ttl_readtable/main.go
Labels: no changelog, no slo, linters
