Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-07, with the labels that each got.

#777 Added details to error from initial discovery
  internal/balancer/balancer.go
Labels: no changelog

#779 Added internal package stack
  internal/stack/record.go
  internal/stack/record_test.go
  internal/xcontext/context_error.go
  internal/xcontext/context_with_timeout.go
  internal/xerrors/stacktrace.go
  internal/xerrors/transport.go
  retry/sql_test.go
Labels: no changelog

#780 Added String method to credentials types
  connection.go
  credentials/credentials.go
  internal/credentials/access_token.go
  internal/credentials/anonymous.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/credentials/multi.go
  internal/credentials/options.go
  internal/credentials/static.go
  internal/credentials/test/credentials_test.go
  internal/meta/test/meta_test.go
Labels: no changelog

#773 feat: implement RowsColumnTypeNullable interface for xsql rows
  internal/xsql/rows.go
  tests/integration/database_sql_get_column_type_test.go
Labels: no changelog, no slo

#786 Add context, topic, partition id to message builder
  internal/topic/topicreaderinternal/message.go
Labels: no changelog

#787 Fix SLO latencies + README
  tests/slo/README.md
  tests/slo/internal/metrics/metrics.go
Labels: no changelog, CI

#791 fix bindings readme
  SQL.md
Labels: no changelog

#789 described retried errors
  retry/retry.go
  tests/integration/table_data_query_with_compression_test.go
  tests/integration/table_scan_error_test.go
  tests/integration/table_scan_query_with_compression_test.go
Labels: enhancement, no changelog

#793 * Fixed `sugar.RemoveRecursive()` for column table type
  .github/workflows/tests.yml
  CHANGELOG.md
  sugar/path.go
  tests/integration/sugar_make_remove_recursive_test.go
Labels: bug

#796 Matrix
  .github/workflows/examples.yml
  .github/workflows/tests.yml
  internal/meta/meta.go
  internal/meta/test/meta_test.go
  internal/meta/version.go
  internal/version/parse.go
  internal/version/parse_test.go
  internal/version/version.go
  log/discovery.go
  log/driver.go
  log/field.go
  log/retry.go
  log/scripting.go
  log/sql.go
  log/table.go
  log/topic.go
  tests/integration/sugar_make_remove_recursive_test.go
  version.go
Labels: no changelog, CI
