Repository ydb-platform/ydb-go-sdk, pull requests merged in 2023-06, with the labels that each got.

#758 test(slo): update to js-version
  .github/workflows/slo.yml
  tests/slo/Dockerfile
  tests/slo/database/sql/main.go
  tests/slo/database/sql/storage.go
  tests/slo/gorm/main.go
  tests/slo/internal/metrics/metrics.go
  tests/slo/internal/workers/workers.go
  tests/slo/native/main.go
  tests/slo/native/storage.go
Labels: no changelog

#764 * Disabled check of node exists with `balancers.SingleConn`
  CHANGELOG.md
  internal/balancer/balancer.go
Labels: bug

#765 * Added `scheme.Entry.IsColumnTable()` helper
  CHANGELOG.md
  scheme/scheme.go
Labels: enhancement

#767 Moved `examples/containers` to `tests/integration/table_containers_test.go`
  CHANGELOG.md
  examples/containers/README.md
  examples/containers/containers.go
  examples/containers/main.go
  internal/table/scanner/scanner.go
  internal/value/value.go
  internal/xsql/valuer.go
  table/types/cast.go
  tests/integration/database_sql_containers_test.go
  tests/integration/table_containers_test.go
Labels: refactoring

#768 made closing connections parallel
  internal/conn/pool.go
Labels: no changelog

#769 enable SLO check only on PRs
  .github/workflows/slo.yml
Labels: no changelog, refactoring, CI

#770 test(slo): xorm fixes
  .github/workflows/slo.yml
  tests/slo/internal/generator/row.go
  tests/slo/xorm/storage.go
Labels: no changelog

#771 refactor: remove not from dropTableIfExists function
  examples/basic/database_sql/series.go
Labels: no changelog, no slo

#772 * Added `sugar.Is{Entry,ColumnTable}Exists` helper
  CHANGELOG.md
  internal/scheme/helpers/check_exists.go
  internal/scheme/helpers/check_exists_test.go
  internal/xsql/conn.go
  scheme/scheme_test.go
  sugar/check_exists.go
Labels: enhancement

#766 * Added `table/types.IsOptional()` helper
  CHANGELOG.md
  table/types/cast.go
  table/types/cast_test.go
Labels: enhancement, no slo

#774 * Added `yd.IsTransactionLocksInvalidated(err)` helper for checks `TL…
  CHANGELOG.md
  errors.go
  internal/xerrors/operation.go
  internal/xerrors/operation_test.go
Labels: enhancement

#775 Update SQL.md
  SQL.md
Labels: no changelog
