Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-02, with the labels that each got.

#1028 fixed gomoddirectives linter
  .golangci.yml
Labels: no changelog

#1050 added ydb-24.1 to intergration tests
  .github/workflows/tests.yml
Labels: no changelog, CI, no slo

#1051 fix mockgen version in CI => check-codegen
  .github/workflows/check-codegen.yml
Labels: no changelog, CI, no slo

#1053 separate types into internal/types package
  internal/decimal/type.go
  internal/scanner/scanner.go
  internal/scripting/client.go
  internal/table/scanner/result.go
  internal/table/scanner/result_test.go
  internal/table/scanner/scan_raw.go
  internal/table/scanner/scanner.go
  internal/table/scanner/scanner_data_test.go
  internal/table/session.go
  internal/table/session_test.go
  internal/types/types.go
  internal/types/types_test.go
  internal/value/type.go
  internal/value/value.go
  internal/value/value_test.go
  internal/xsql/rows.go
  internal/xsql/valuer.go
  table/options/models.go
  table/options/options.go
  table/options/options_test.go
  table/result/indexed/indexed.go
  table/result/result.go
  table/table.go
  table/types/types.go
  table/types/value.go
  testutil/compare_test.go
Labels: no changelog, refactoring

#1057 return ErrCommitToExpiredSession for commit to stopped partitions
  CHANGELOG.md
  internal/topic/topicreaderinternal/stream_reader_impl.go
Labels: bug

#1043 enable protogetter linter
  .github/workflows/check-codegen.yml
  .github/workflows/tests.yml
  .golangci.yml
  CHANGELOG.md
  internal/decimal/type.go
  internal/discovery/discovery.go
  internal/grpcwrapper/rawtopic/rawtopicreader/rawtopicreader.go
  internal/operation/status.go
  internal/scanner/scanner.go
  internal/scripting/client.go
  internal/table/scanner/result.go
  internal/table/scanner/result_test.go
  internal/table/scanner/scan_raw.go
  internal/table/scanner/scanner.go
  internal/table/scanner/scanner_data_test.go
  internal/table/session.go
  internal/table/session_test.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/types/types.go
  internal/types/types_test.go
  internal/value/type.go
  internal/value/value.go
  internal/value/value_test.go
  internal/version/version.go
  internal/xerrors/operation.go
  internal/xsql/rows.go
  internal/xsql/valuer.go
  table/options/models.go
  table/options/options.go
  table/options/options_test.go
  table/result/indexed/indexed.go
  table/result/result.go
  table/table.go
  table/types/types.go
  table/types/value.go
  testutil/compare_test.go
Labels: no changelog

#1055 params builder
  CHANGELOG.md
  internal/bind/bind.go
  internal/bind/params.go
  internal/bind/params_test.go
  internal/params/builder.go
  internal/params/builder_test.go
  internal/params/list.go
  internal/params/list_test.go
  internal/params/optional.go
  internal/params/optional_test.go
  internal/params/parameters.go
  internal/params/parameters_test.go
  internal/scripting/client.go
  internal/table/params.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/value/value.go
  internal/xsql/conn.go
  internal/xsql/tx.go
  params_builder.go
  query_bind_test.go
  scripting/scripting.go
  sugar/params.go
  table/table.go
  tests/integration/database_sql_containers_test.go
Labels: enhancement

#1003 QueryClient API
  CHANGELOG.md
  connection.go
  driver.go
  go.mod
  go.sum
  internal/allocator/allocator.go
  internal/query/client.go
  internal/query/client_test.go
  internal/query/column.go
  internal/query/config/config.go
  internal/query/config/options.go
  internal/query/errors.go
  internal/query/execute_query.go
  internal/query/execute_query_test.go
  internal/query/grpc_client_mock_test.go
  internal/query/pool.go
  internal/query/result.go
  internal/query/result_set.go
  internal/query/result_set_test.go
  internal/query/result_test.go
  internal/query/row.go
  internal/query/scanner_data.go
  internal/query/scanner_indexed.go
  internal/query/scanner_named.go
  internal/query/scanner_struct.go
  internal/query/session.go
  internal/query/session_test.go
  internal/query/transaction.go
  internal/query/transaction_test.go
  internal/session/status.go
  options.go
  query/client.go
  query/column.go
  query/do_options.go
  query/do_tx_options.go
  query/example_test.go
  query/execute_options.go
  query/named.go
  query/named_test.go
  query/options.go
  query/result.go
  query/session.go
  query/session_status.go
  query/transaction.go
  query/transaction_control.go
  query/transaction_settings.go
  tests/integration/query_execute_test.go
  tests/integration/query_tx_execute_test.go
  trace/query.go
Labels: enhancement

#1031 Enable maligned linter
  .golangci.yml
  driver.go
  internal/background/worker.go
  internal/coordination/config/config.go
  internal/grpcwrapper/rawtopic/rawtopicreader/messages.go
  internal/grpcwrapper/rawtopic/rawtopicwriter/messages.go
  internal/ratelimiter/config/config.go
  internal/scheme/config/config.go
  internal/table/session.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/topic/topicwriterinternal/message.go
  internal/topic/topicwriterinternal/writer_reconnector.go
  internal/topic/topicwriterinternal/writer_single_stream.go
  log/logger.go
Labels: no changelog
