Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-04, with the labels that each got.

#1186 use errgroup for close internal/pool
  internal/pool/pool.go
Labels: no changelog, refactoring, no slo

#1185 * Updated the indirect dependencies `golang.org/x/net` to `v0.17.0` and `golang.org/x/sys` to `v0.13.0` due to vulnerability issue
  CHANGELOG.md
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  tests/slo/go.mod
  tests/slo/go.sum
Labels: dependencies

#1188 added xcontext.CancelsGuard
  internal/conn/conn.go
  internal/xcontext/cancels_quard.go
  internal/xcontext/cancels_quard_test.go
Labels: no changelog, refactoring

#1189 updated actions checkout, setup-go, golangci-lint-action, codeql-actions and upload-artifact
  .github/workflows/breaking.yml
  .github/workflows/changelog.yml
  .github/workflows/check-codegen.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/examples.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/slo.yml
  .github/workflows/tests.yml
Labels: no changelog, tech debt

#1192 * Supported `table.Session.RenameTables` method
  CHANGELOG.md
  internal/table/session.go
  internal/table/session_test.go
  table/options/options.go
  table/table.go
Labels: enhancement

#1193 moved internal/conn.lastUsage into internal/xsync package
  internal/conn/conn.go
  internal/conn/last_usage.go
  internal/xsync/last_usage_guard.go
  internal/xsync/last_usage_guard_test.go
Labels: no changelog, refactoring

#1048 enable gomnd linter
  .golangci.yml
  internal/allocator/allocator.go
  internal/backoff/backoff.go
  internal/balancer/local_dc.go
  internal/cmd/gtrace/main.go
  internal/cmd/gtrace/writer.go
  internal/conn/pool.go
  internal/coordination/client.go
  internal/coordination/session.go
  internal/credentials/static.go
  internal/decimal/decimal.go
  internal/grpcwrapper/rawtopic/rawtopicwriter/streamwriter.go
  internal/meta/context.go
  internal/repeater/repeater.go
  internal/secret/token.go
  internal/stack/record.go
  internal/table/client.go
  internal/table/scanner/result.go
  internal/table/scanner/scanner.go
  internal/topic/retriable_error.go
  internal/topic/topicreaderinternal/committer.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicwriterinternal/encoders.go
  internal/topic/topicwriterinternal/queue.go
  internal/topic/topicwriterinternal/writer_reconnector.go
  internal/value/time.go
  internal/value/value.go
  internal/version/parse.go
  retry/retry.go
  table/types/types.go
  tests/slo/database/sql/storage.go
  tests/slo/internal/config/config.go
  tests/slo/internal/metrics/metrics.go
  tests/slo/native/query/storage.go
  tests/slo/native/table/storage.go
  testutil/compare.go
Labels: no changelog, refactoring

#1196 * Added processing of `Ydb.StatusIds_EXTERNAL_ERROR` in `retry.Retry`
  CHANGELOG.md
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  retry/errors_data_test.go
  tests/slo/go.mod
  tests/slo/go.sum
Labels: enhancement

#1203 Fixed data race using `log.WithNames`
  CHANGELOG.md
  log/context.go
  log/context_test.go
Labels: bug

#1211 Enabled `containedctx` linter
  .golangci.yml
  CHANGELOG.md
  driver.go
  examples/topic/topicreader/topicreader_trace.go
  internal/background/worker.go
  internal/conn/conn.go
  internal/conn/grpc_client_stream.go
  internal/coordination/client_test.go
  internal/coordination/session.go
  internal/meta/context_test.go
  internal/operation/params_test.go
  internal/query/row.go
  internal/table/scanner/result_test.go
  internal/topic/topicreaderinternal/partition_session.go
  internal/topic/topicreaderinternal/reader.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/topic/topicwriterinternal/writer_reconnector_test.go
  internal/xcontext/context_with_cancel.go
  internal/xcontext/context_with_timeout.go
  internal/xcontext/without_deadline.go
  internal/xsql/conn.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  log/context_test.go
  trace/sql.go
  trace/sql_gtrace.go
  trace/topic.go
  trace/topic_gtrace.go
Labels: refactoring, linters

#1184 added experimental `retry/budget` package
  CHANGELOG.md
  config/config.go
  internal/backoff/delay.go
  internal/backoff/delay_test.go
  internal/balancer/balancer.go
  internal/config/config.go
  internal/coordination/client.go
  internal/query/options/retry.go
  internal/ratelimiter/client.go
  internal/scheme/client.go
  internal/scheme/config/config.go
  internal/scripting/client.go
  internal/table/retry.go
  internal/topic/topicclientinternal/client.go
  internal/wait/wait.go
  internal/xerrors/join.go
  internal/xerrors/join_test.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  options.go
  query/client.go
  retry/budget/budget.go
  retry/budget/budget_test.go
  retry/budget/errors.go
  retry/retry.go
  retry/retry_test.go
  retry/sql.go
  sql.go
  table/table.go
  tests/integration/retry_budget_test.go
  tests/slo/database/sql/storage.go
  tests/slo/native/query/storage.go
  tests/slo/native/table/storage.go
Labels: enhancement

#1171 Enable funlen linter (part 2)
  internal/allocator/allocator.go
  internal/decimal/decimal.go
  internal/decimal/decimal_test.go
  internal/stack/record.go
  internal/stack/record_test.go
  internal/types/types.go
  retry/retry.go
  retry/retry_test.go
Labels: no changelog
