Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-11, with the labels that each got.

#1538 * Changed behaviour on re-discovery: always open new grpc connection for discovery request
  CHANGELOG.md
  balancer.go
  driver.go
  internal/balancer/balancer.go
  internal/balancer/local_dc_test.go
  internal/discovery/discovery.go
  internal/discovery/discovery_test.go
  internal/meta/meta.go
  internal/meta/trace_id.go
  log/driver.go
  options.go
  with.go
Labels: discovery, core

#1541 * Fixed closing of child driver with shared balancer
  CHANGELOG.md
  driver.go
  dsn_test.go
  options.go
  tests/integration/driver_secure_test.go
  tests/integration/driver_test.go
  with.go
  with_test.go
Labels: bug, balancer

#1545 Small broken change: Fixed `traceparent` header for tracing grpc requests + * Added method `ID()` into `spans.Span` interface
  CHANGELOG.md
  spans/driver.go
  spans/driver_test.go
  spans/spans.go
Labels: OpenTelemetry

#1549 Preferred nodeID
  CHANGELOG.md
  context.go
  internal/pool/pool.go
  internal/pool/pool_test.go
Labels: balancer

#1554 Removed balancer.OnUpdate
  internal/balancer/balancer.go
Labels: no changelog, balancer

#1168 * Refactored coordination traces
  CHANGELOG.md
  coordination/client.go
  internal/coordination/client.go
  internal/coordination/session.go
  log/coordination.go
  tests/integration/coordination_test.go
  trace/coordination.go
  trace/coordination_gtrace.go
Labels: coordination

#1498 improove error text
  internal/topic/topicreadercommon/committer.go
Labels: enhancement, no changelog, no slo

#1557 gRPC connection will be forcefully closed on DNS resolver errors from…
  CHANGELOG.md
  config/config.go
  config/defaults.go
  driver_string_test.go
  internal/balancer/balancer.go
  internal/conn/conn.go
  internal/conn/pool.go
Labels: refactoring

#1558 rename call.FunctionID() to call.String()
  internal/stack/function_id.go
  internal/stack/function_id_test.go
  internal/stack/record.go
  internal/stack/record_test.go
  retry/retry.go
  spans/discovery.go
  spans/driver.go
  spans/query.go
  spans/retry.go
  spans/scheme.go
  spans/scripting.go
  spans/sql.go
  spans/table.go
  trace/call.go
Labels: refactoring

#1551 `sugar.DSN` refactoring + added test for static credentials
  CHANGELOG.md
  internal/xerrors/operation.go
  sugar/dsn.go
  sugar/dsn_test.go
  tests/integration/driver_test.go
Labels: tests

#1564 * Fixed string representation of `TzTimestamp`, `TzDatetime` and `TzDate` type values + Added `database/sql/driver.Value` as type destination for almost ydb values
  CHANGELOG.md
  internal/params/builder_test.go
  internal/params/dict_test.go
  internal/params/list_test.go
  internal/params/optional_test.go
  internal/params/set_test.go
  internal/params/struct_test.go
  internal/params/tuple_test.go
  internal/params/variant_struct_test.go
  internal/params/variant_tuple_test.go
  internal/value/cast_test.go
  internal/value/time.go
  internal/value/value.go
Labels: refactoring, database/sql, yql

#1565 enable_antlr4_parser in experiment tests
  .github/workflows/tests.yml
  tests/integration/table_scan_error_test.go
Labels: CI

#1567 Slo chaos testing
  .github/workflows/slo.yml
  tests/slo/internal/metrics/metrics.go
Labels: no tests
