Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-08, with the labels that each got.

#1387 moved `internal/query/tx.{Identifier,ID}` to new package `internal/tx`
  internal/query/transaction.go
  internal/query/tx/control.go
  internal/table/session.go
  internal/table/session_test.go
  internal/table/transaction.go
  internal/tx/id.go
  internal/xsql/conn.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  query/transaction.go
  table/table.go
Labels: refactoring, no slo, query-service, tx

#1383 run experimental tests on nightly ydb image
  .github/workflows/tests.yml
  tests/integration/database_sql_static_credentials_test.go
  tests/integration/static_credentials_test.go
Labels: no changelog, no slo

#1389 script for run linters local
  .github/scripts/golangci-lint-gen-configs.sh
  .github/scripts/golangci-lint.sh
  .github/workflows/lint.yml
  examples/.gitignore
  tests/slo/.gitignore
Labels: no changelog, no slo

#1393 Add guarantee about memory release from the message content
  internal/topic/topicreadercommon/message.go
Labels: no changelog, no slo

#1394 * Fixed bug with nil pointer dereference on trace callback from `query.createSession`
  CHANGELOG.md
  internal/query/session.go
  internal/query/session_test.go
Labels: bug

#1354 Read messages within transaction
  .github/workflows/tests.yml
  CHANGELOG.md
  examples/topic/topicreader/stubs.go
  examples/topic/topicreader/topic_reader_transaction.go
  examples/topic/topicreader/topicreader_advanced.go
  examples/topic/topicreader/topicreader_handler.go
  examples/topic/topicreader/topicreader_show.go
  examples/topic/topicreader/topicreader_simple.go
  examples/topic/topicreader/topicreader_trace.go
  internal/grpcwrapper/rawtopic/client.go
  internal/grpcwrapper/rawtopic/update_offset_in_transaction.go
  internal/grpcwrapper/rawtopic/update_offset_in_transaction_test.go
  internal/grpcwrapper/rawydb/operation_params.go
  internal/operation/mode.go
  internal/query/errors.go
  internal/query/result.go
  internal/query/session_fixtures_test.go
  internal/query/transaction.go
  internal/query/transaction_fixtures_test.go
  internal/query/transaction_test.go
  internal/query/tx/control.go
  internal/topic/topicclientinternal/client.go
  internal/topic/topiclistenerinternal/stream_listener.go
  internal/topic/topicreadercommon/message.go
  internal/topic/topicreadercommon/read_partition_session.go
  internal/topic/topicreaderinternal/batched_stream_reader_interface.go
  internal/topic/topicreaderinternal/batched_stream_reader_mock_test.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/reader.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/topic/topicreaderinternal/stream_reconnector_test.go
  internal/topic/topicreaderinternal/topic_client_interface.go
  internal/topic/topicreaderinternal/topic_client_interface_mock_test.go
  internal/topic/topicreaderinternal/transaction_mock_test.go
  internal/tx/id.go
  internal/tx/transaction.go
  tests/integration/helpers_test.go
  tests/integration/topic_listener_test.go
  tests/integration/topic_transactions_test.go
  topic/topicreader/reader.go
Labels: no slo

#1397 remove usage deprecated methods of fixenv
  tests/integration/helpers_test.go
Labels: no changelog, no slo

#1400 Fix drop table in tests helper
  tests/integration/helpers_test.go
Labels: no changelog, no slo

#1401 * Removed support of `go1.20`
  .github/workflows/examples.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  balancers/balancers.go
  go.mod
  go.sum
  internal/xcontext/done.go
  internal/xcontext/done_go1.20.go
  internal/xcontext/done_test.go
  internal/xcontext/value_only.go
  internal/xcontext/without_deadline_go1.20.go
  internal/xmath/ordered.go
  internal/xmath/ordered_go1.20.go
  internal/xmath/xmath.go
  internal/xmath/xmath_test.go
  internal/xslices/clone.go
  internal/xslices/clone_1.20.go
  internal/xslices/diff.go
  internal/xslices/sort.go
  internal/xslices/sort_copy.go
  internal/xslices/sort_go1.20.go
  internal/xslices/sort_test.go
  internal/xsync/last_usage_guard_start.go
  internal/xsync/last_usage_guard_start_go1.20.go
Labels: refactoring, CI

#1402 fixed possible multiply calls notifiers about stop transaction
  internal/query/transaction.go
Labels: no changelog

#1396 Refactoring of `query.Result`
  .github/workflows/examples.yml
  CHANGELOG.md
  example_test.go
  examples/basic/native/query/series.go
  examples/go.mod
  internal/query/client.go
  internal/query/client_test.go
  internal/query/errors.go
  internal/query/execute_query.go
  internal/query/execute_query_test.go
  internal/query/result.go
  internal/query/result_range_test.go
  internal/query/result_set.go
  internal/query/result_set_range_test.go
  internal/query/result_set_test.go
  internal/query/result_test.go
  internal/query/session.go
  internal/query/transaction.go
  internal/query/transaction_test.go
  query/example_test.go
  query/result.go
  sugar/result.go
  tests/integration/query_execute_test.go
  tests/integration/query_multi_result_sets_test.go
  tests/integration/query_range_test.go
  tests/integration/query_tx_execute_test.go
  tests/slo/native/query/internal/storage.go
Labels: refactoring, query-service, internal

#1404 * Changed result type of `query.Session.NodeID()` from `int64` to `ui…
  CHANGELOG.md
  internal/query/session.go
  query/session.go
  trace/query.go
Labels: refactoring, query-service

#1405 fix gstack codegen for function ID
  driver.go
  internal/balancer/balancer.go
  internal/cmd/gstack/utils/utils.go
  internal/conn/conn.go
  internal/conn/grpc_client_stream.go
  internal/conn/pool.go
  internal/coordination/client.go
  internal/discovery/discovery.go
  internal/meta/meta.go
  internal/pool/pool.go
  internal/query/client.go
  internal/query/result.go
  internal/query/result_set.go
  internal/query/row.go
  internal/query/session.go
  internal/query/transaction.go
  internal/repeater/repeater.go
  internal/scheme/client.go
  internal/scripting/client.go
  internal/table/client.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/version/version.go
  internal/xresolver/xresolver.go
  internal/xsql/conn.go
  internal/xsql/connector.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/tx_fake.go
  retry/retry.go
  retry/sql.go
  with.go
Labels: no changelog, refactoring, no slo

#1408 Do not create new items if index is full
  CHANGELOG.md
  internal/pool/pool.go
  internal/pool/pool_test.go
Labels: bug, query-service

#1409 go1.23
  .github/workflows/breaking.yml
  .github/workflows/check-codegen.yml
  .github/workflows/examples.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: no changelog, CI, internal

#1410 fixed build tags for range-over
  .github/workflows/tests.yml
  CHANGELOG.md
  internal/query/result_range_test.go
  internal/query/result_set_range_test.go
  internal/xiter/xiter.go
  internal/xiter/xiter_experiment_go1.23.go
  query/example_test.go
  query/result.go
  tests/integration/query_range_test.go
Labels: no slo

#1406 Changed query.Client API
  CHANGELOG.md
  example_test.go
  examples/basic/native/query/main.go
  examples/basic/native/query/series.go
  examples/topic/topicreader/topic_reader_transaction.go
  internal/query/client.go
  internal/query/client_test.go
  internal/query/execute_query.go
  internal/query/execute_query_test.go
  internal/query/options/execute.go
  internal/query/result.go
  internal/query/result_set.go
  internal/query/result_test.go
  internal/query/session.go
  internal/query/session_fixtures_test.go
  internal/query/session_test.go
  internal/query/transaction.go
  internal/query/transaction_fixtures_test.go
  internal/query/transaction_test.go
  internal/query/tx/control.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicreaderinternal/transaction_mock_test.go
  internal/tx/id.go
  internal/tx/transaction.go
  internal/xsync/set.go
  log/query.go
  log/topic.go
  metrics/query.go
  query/client.go
  query/example_test.go
  query/result.go
  query/session.go
  query/stats.go
  query/transaction.go
  sugar/example_test.go
  sugar/query_test.go
  tests/integration/query_execute_test.go
  tests/integration/query_multi_result_sets_test.go
  tests/integration/query_range_test.go
  tests/integration/query_read_row_test.go
  tests/integration/query_tx_execute_test.go
  tests/integration/sugar_result_test.go
  tests/integration/sugar_unmarhall_result_set_test.go
  tests/integration/sugar_unmarhall_row_test.go
  tests/integration/topic_transactions_test.go
  tests/slo/native/query/internal/storage.go
  topic/topicreader/reader.go
  trace/query.go
  trace/query_gtrace.go
  trace/session_info.go
  trace/sql.go
  trace/sql_gtrace.go
  trace/table.go
  trace/table_gtrace.go
  trace/topic.go
  trace/topic_gtrace.go
  trace/tx_info.go
Labels: refactoring, query-service

#1412 * Added experimental support for executing scripts over query service…
  CHANGELOG.md
  internal/coordination/conversation/conversation.go
  internal/discovery/discovery_test.go
  internal/query/client.go
  internal/query/client_test.go
  internal/query/execute_query.go
  internal/query/options/execute_script.go
  internal/query/result.go
  internal/query/result/result.go
  internal/query/result_set.go
  internal/query/result_set_range_test.go
  internal/query/result_set_test.go
  internal/query/row.go
  internal/topic/topicreaderinternal/batcher_test.go
  internal/xtest/must.go
  internal/xtest/must_test.go
  log/query.go
  query/client.go
  query/result.go
  sugar/query_test.go
  tests/integration/helpers_test.go
  tests/integration/query_execute_script_test.go
  tests/integration/topic_listener_test.go
  tests/integration/topic_transactions_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: query-service

#1416 make option `query.WithIdempotent()` as option for `query.Client.{Exec,Query,QueryResultSet,QueryRow}`
  CHANGELOG.md
  example_test.go
  internal/query/client.go
  internal/query/execute_query.go
  internal/query/options/execute.go
  internal/query/options/retry.go
  internal/query/session.go
  internal/query/transaction.go
  internal/query/transaction_test.go
  query/example_test.go
  tests/integration/query_execute_test.go
  tests/integration/query_multi_result_sets_test.go
  tests/integration/query_range_test.go
  tests/integration/query_read_row_test.go
Labels: refactoring, query-service

#1417 added type `operation.kind` for `operation.Client.List` method
  operation/client.go
  operation/example_test.go
  operation/kind.go
  tests/integration/operation_test.go
Labels: no changelog, refactoring

#1418 refactoring of internal/pool
  internal/pool/errors.go
  internal/pool/pool.go
  internal/pool/pool_test.go
Labels: no changelog, query-service

#1421 internal/pool async create and close item
  internal/pool/errors.go
  internal/pool/pool.go
  internal/pool/pool_test.go
  internal/pool/stats.go
  internal/query/client.go
  internal/xsync/mutex.go
  internal/xsync/mutex_test.go
  internal/xsync/set.go
  internal/xsync/value.go
  internal/xsync/value_test.go
  metrics/query.go
  operation/example_test.go
  tests/integration/operation_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: no changelog, query-service

#1426 splitted `operation.List` to five list operations `operation.List{BuildIndex,ImportFromS3,ExportToS3,ExportToYT,ExecuteQuery}`
  CHANGELOG.md
  internal/operation/metadata/metadata.go
  internal/query/client.go
  internal/query/options/execute_script.go
  operation/client.go
  operation/example_test.go
  operation/kind.go
  tests/integration/operation_test.go
Labels: operation-service

#1427 Do tx settings
  internal/query/errors.go
  internal/query/options/execute.go
  internal/query/transaction.go
  tests/integration/query_tx_execute_test.go
Labels: no changelog, query-service
