Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-07, with the labels that each got.

#1317 * Added `query.{Client,Result}.Stats()` method
  CHANGELOG.md
  internal/query/client_test.go
  internal/query/result.go
  internal/query/result_test.go
  internal/stats/query.go
  internal/stats/query_test.go
  internal/table/scanner/result.go
  internal/table/scanner/stats.go
  log/query.go
  query/client.go
  query/result.go
  query/stats.go
  sugar/query_test.go
  table/stats/stats.go
  tests/integration/basic_example_native_test.go
  tests/integration/query_execute_test.go
  tests/integration/table_multiple_result_sets_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: enhancement, query-service

#1315 Fix linter
  internal/conn/conn.go
  internal/credentials/static.go
  internal/decimal/decimal.go
  internal/topic/topicwriterinternal/writer_reconnector.go
Labels: no changelog

#1324 upgraded grpc dependency
  CHANGELOG.md
  go.mod
  go.sum
Labels: dependencies

#1325 fixed the processing io.EOF on grpc streams
  internal/conn/grpc_client_stream.go
Labels: no changelog, refactoring

#1326 added timestamp to SLO log msgs
  tests/slo/internal/workers/metrics.go
  tests/slo/internal/workers/read.go
  tests/slo/internal/workers/workers.go
  tests/slo/internal/workers/write.go
Labels: no changelog, refactoring, SLO

#1329 Added internal/xlist + switched internal/table.Client from container/list to internal/xlist
  internal/table/client.go
  internal/table/client_test.go
  internal/xlist/list.go
  internal/xlist/list_test.go
Labels: no changelog, refactoring

#1331 moved internal/allocator.Pool into internal/xsync package
  internal/allocator/allocator.go
  internal/xsync/pool.go
  internal/xsync/pool_test.go
Labels: no changelog, refactoring

#1334 Added endpoint.Diff
  internal/endpoint/diff.go
  internal/endpoint/diff_test.go
Labels: no changelog, internal

#1336 Added xsync.Map
  internal/xsync/map.go
  internal/xsync/map_test.go
Labels: no changelog, internal

#1338 moved internal/pool/stats.Stats to internal/pool.Stats
  internal/pool/pool.go
  internal/pool/stats.go
  internal/pool/trace.go
  internal/query/client.go
  query/client.go
  query/stats.go
  sugar/query_test.go
Labels: no changelog, refactoring, query-service

#1340 added internal/xerrors.WithNodeID(nodeID) option + removed internal/c…
  CHANGELOG.md
  internal/conn/conn.go
  internal/conn/conn_test.go
  internal/conn/error.go
  internal/conn/error_test.go
  internal/conn/grpc_client_stream.go
  internal/credentials/oauth2.go
  internal/credentials/oauth2_test.go
  internal/table/session.go
  internal/xerrors/check.go
  internal/xerrors/issues.go
  internal/xerrors/operation.go
  internal/xerrors/retryable.go
  internal/xerrors/transport.go
  retry/retry.go
  retry/retry_test.go
  retry/sql_test.go
  tests/integration/table_data_query_issue_row_col_test.go
Labels: no changelog, refactoring

#1339 refactoring of xsync.OnceValue
  driver.go
  internal/xsync/once.go
  internal/xsync/once_test.go
Labels: no changelog, refactoring

#1342 removed `endpoint.Diff` + added `xslices.{Transform,Diff}`
  internal/endpoint/diff.go
  internal/endpoint/diff_test.go
  internal/xslices/diff.go
  internal/xslices/diff_test.go
  internal/xslices/sort.go
  internal/xslices/sort_go1.20.go
  internal/xslices/sort_test.go
  internal/xslices/transform.go
  internal/xslices/transform_test.go
Labels: no changelog, refactoring, internal

#1343 fixed flaky TestOauth2TokenExchange
  internal/credentials/oauth2_test.go
Labels: no changelog, CI, tests, no slo, flaky

#1344 switched balancer private func endpointsDiff to xslices.Diff
  internal/balancer/balancer.go
  internal/balancer/balancer_test.go
  internal/balancer/connections_state.go
Labels: no changelog, refactoring, internal

#1345 switched internal/balancer.Balancer.connections_state from pointer to atomic.Pointer
  internal/balancer/balancer.go
Labels: no changelog, refactoring

#1346 added xslices.Map and xslices.Filter
  internal/xslices/map.go
  internal/xslices/map_test.go
  internal/xslices/split.go
  internal/xslices/split_test.go
Labels: no changelog, refactoring, internal

#1347 * Changed signature of filter func in balancers (replaced argument from `conn.Conn` type to `endpoint.Info`)
  CHANGELOG.md
  balancers/balancers.go
  balancers/balancers_test.go
  balancers/config_test.go
  internal/balancer/config/routerconfig.go
  internal/balancer/connections_state.go
  internal/balancer/connections_state_test.go
Labels: refactoring, balancer

#1348 fixed TestErrorInHTTPRequest
  internal/credentials/oauth2_test.go
Labels: no changelog, CI, tests, no slo, internal

#1349 Fixed build for go1.20
  CHANGELOG.md
  internal/xslices/diff_test.go
  internal/xslices/sort.go
  internal/xslices/sort_copy.go
  internal/xslices/sort_copy_test.go
  internal/xslices/sort_go1.20.go
  internal/xslices/sort_test.go
Labels: bug, CI, no slo, internal

#1351 * Fixed `internal/xstrings.Buffer()` leak without call `buffer.Free()`
  CHANGELOG.md
  internal/xerrors/issues.go
  internal/xerrors/retryable.go
  internal/xerrors/transport.go
Labels: bug, no slo, internal

#1353 Added xslices.Split + refactored xslices.Filter
  internal/xslices/filter.go
  internal/xslices/filter_test.go
  internal/xslices/split.go
  internal/xslices/split_test.go
Labels: no changelog, refactoring, no slo, internal

#1355 added internal/balancer/state package
  internal/balancer/state/errors.go
  internal/balancer/state/state.go
  internal/balancer/state/state_test.go
Labels: no changelog, refactoring, no slo, internal, balancer

#1356 renamed internal/balancer/state => internal/balancer/cluster
  internal/balancer/cluster/cluster.go
  internal/balancer/cluster/cluster_test.go
  internal/balancer/cluster/errors.go
Labels: no changelog, refactoring, no slo, internal, balancer

#1357 added `internal/xsync.Map.Delete` + `internal/xsync.Set`
  internal/xsync/map.go
  internal/xsync/set.go
  internal/xsync/set_test.go
Labels: no changelog, refactoring, no slo, internal

#1359 empty types are aliases now
  internal/empty/empty.go
Labels: no changelog

#1360 extract common topic code to dedicated package, prepare for topic listener
  internal/topic/topicreadercommon/batch.go
  internal/topic/topicreadercommon/batch_test.go
  internal/topic/topicreadercommon/commit_range.go
  internal/topic/topicreadercommon/commit_range_test.go
  internal/topic/topicreadercommon/const.go
  internal/topic/topicreadercommon/decoders.go
  internal/topic/topicreadercommon/init_message.go
  internal/topic/topicreadercommon/message.go
  internal/topic/topicreadercommon/message_content_pool.go
  internal/topic/topicreadercommon/message_content_pool_test.go
  internal/topic/topicreadercommon/one_time_reader.go
  internal/topic/topicreadercommon/one_time_reader_test.go
  internal/topic/topicreadercommon/partition_session_storage.go
  internal/topic/topicreadercommon/pool_interface_mock_test.go
  internal/topic/topicreadercommon/read_partition_session.go
  internal/topic/topicreadercommon/read_selector.go
  internal/topic/topicreadercommon/reader_id.go
  internal/topic/topicreadercommon/split_batches.go
  internal/topic/topicreaderinternal/batched_stream_reader_interface.go
  internal/topic/topicreaderinternal/batched_stream_reader_mock_test.go
  internal/topic/topicreaderinternal/batcher.go
  internal/topic/topicreaderinternal/batcher_test.go
  internal/topic/topicreaderinternal/commit_range.go
  internal/topic/topicreaderinternal/commit_range_test.go
  internal/topic/topicreaderinternal/committer.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/partition_session.go
  internal/topic/topicreaderinternal/public_callbacks.go
  internal/topic/topicreaderinternal/reader.go
  internal/topic/topicreaderinternal/reader_test.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/topic/topicreaderinternal/stream_reconnector_test.go
  testutil/topic.go
  topic/topicoptions/topicoptions_reader.go
  topic/topicreader/errors.go
  topic/topicreader/reader.go
  trace/topic.go
  trace/topic_gtrace.go
Labels: no changelog

#1362 fix oauth test logs and remove many time execution
  internal/credentials/oauth2_test.go
Labels: no changelog, no slo

#1365 Fixed respect to query.WithCommit() flag for tx.Execute in query service
  CHANGELOG.md
  internal/query/options/execute.go
  internal/query/transaction_test.go
  tests/integration/helpers_test.go
  tests/integration/query_tx_execute_test.go
Labels: bug

#1363 Fix listener stop partition
  CHANGELOG.md
  examples/topic/topicreader/topicreader_handler.go
  internal/topic/topiclistenerinternal/event_handler.go
  internal/topic/topiclistenerinternal/event_handler_mock_test.go
  internal/topic/topiclistenerinternal/stream_listener.go
  internal/topic/topiclistenerinternal/stream_listener_test.go
  tests/integration/topic_listener_test.go
  topic/topiclistener/event_handler.go
Labels: no changelog

#1368 renamed tx.Parent to tx.ID
  internal/query/transaction.go
  internal/query/tx/id.go
Labels: no changelog, no slo, query-service

#1370 internal/xsync improvements
  internal/xsync/map.go
  internal/xsync/map_test.go
  internal/xsync/set.go
  internal/xsync/set_test.go
Labels: enhancement, no changelog, refactoring, no slo

#1371 xerrors improvements
  internal/balancer/balancer.go
  internal/conn/errors.go
  internal/conn/errors_test.go
  internal/xerrors/pessimized_error_test.go
  internal/xerrors/retryable.go
  internal/xerrors/transport.go
  internal/xerrors/transport_test.go
Labels: no changelog, refactoring, no slo

#1374 move offset to topiccommon
  internal/grpcwrapper/rawtopic/rawtopiccommon/offset.go
  internal/grpcwrapper/rawtopic/rawtopiccommon/rangeoffset.go
  internal/grpcwrapper/rawtopic/rawtopicreader/messages.go
  internal/topic/topiclistenerinternal/stream_listener.go
  internal/topic/topiclistenerinternal/stream_listener_test.go
  internal/topic/topicreadercommon/commit_range.go
  internal/topic/topicreadercommon/commit_range_test.go
  internal/topic/topicreadercommon/read_partition_session.go
  internal/topic/topicreaderinternal/batcher_test.go
  internal/topic/topicreaderinternal/committer.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/public_callbacks.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
Labels: no changelog, no slo

#1375 fixed typo
  internal/query/client.go
Labels: no changelog, no slo

#1378 skip changelog step instead on cancel/abort
  .github/workflows/changelog.yml
Labels: no changelog, no slo

#1376 make transaction internal public
  internal/query/execute_query.go
  internal/query/session.go
  internal/query/transaction.go
Labels: no changelog, no slo

#1377 separate namespace for scheduled and event tests for prevent stop one…
  .github/workflows/tests.yml
Labels: no changelog, no slo

#1381 fix builder methods return self
  CHANGELOG.md
  internal/topic/topicreadercommon/message.go
Labels: no changelog, no slo

#1380 fix internal name typo
  internal/topic/topicreadercommon/batch.go
Labels: no changelog, no slo

#1384 Added early exit from `xtest.TestManyTimes()` on `-short` flag
  internal/xtest/manytimes.go
Labels: no changelog, refactoring, tests, no slo

#1385 Skipped nil errors in `xerrors.Join(errs)`
  internal/xerrors/join.go
  internal/xerrors/join_test.go
Labels: no changelog, refactoring, no slo

#1373 added throwing create session error to result error from `internal/table.Client.internalPoolGet`
  internal/table/client.go
  internal/table/client_test.go
  internal/table/errors.go
  internal/table/retry_test.go
  internal/table/session.go
Labels: no changelog, refactoring, no slo
