Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-05, with the labels that each got.

#1217 Trace stream finish
  CHANGELOG.md
  internal/conn/conn.go
  internal/conn/grpc_client_stream.go
  internal/xcontext/cancels_quard.go
  internal/xcontext/cancels_quard_test.go
  internal/xtest/grpclogger.go
  log/driver.go
  metrics/driver.go
  trace/details.go
  trace/driver.go
  trace/driver_gtrace.go
Labels: refactoring

#1218 fixed OAuth2 test
  CHANGELOG.md
  internal/credentials/oauth2_test.go
Labels: bug, CI

#1220 added `xcontext.WithDone()` + replaced custom implementation `xcontext.ValueOnly()` to standard `context.WithoutCancel()`
  internal/xcontext/done.go
  internal/xcontext/done_test.go
  internal/xcontext/without_deadline.go
Labels: no changelog, refactoring

#1226 * Added `ydb.WithNodeAddressMutator` option for mutate original node …
  CHANGELOG.md
  internal/discovery/config/config.go
  internal/discovery/discovery.go
  internal/discovery/discovery_test.go
  internal/discovery/grpc_client_mock_test.go
  internal/endpoint/endpoint.go
  options.go
Labels: enhancement

#1231 Fixed data race on close topic writer
  CHANGELOG.md
  internal/background/worker.go
  internal/topic/topicwriterinternal/writer_reconnector.go
  internal/topic/topicwriterinternal/writer_reconnector_test.go
Labels: no changelog, no slo

#1233 upgraded gorm-driver
  examples/auth/environ/main.go
  examples/basic/database_sql/main.go
  examples/basic/gorm/main.go
  examples/basic/native/query/main.go
  examples/basic/native/table/main.go
  examples/coordination/lock/main.go
  examples/coordination/workers/main.go
  examples/ddl/main.go
  examples/decimal/main.go
  examples/describe/main.go
  examples/go.mod
  examples/go.sum
  examples/pagination/main.go
  examples/read_table/main.go
  examples/serverless/healthcheck/main.go
  examples/serverless/healthcheck/service.go
  examples/serverless/url_shortener/main.go
  examples/serverless/url_shortener/service.go
  examples/topic/cdc-fill-and-read/main.go
  examples/ttl/main.go
  examples/ttl_readtable/main.go
  tests/slo/go.mod
  tests/slo/go.sum
  tests/slo/gorm/storage.go
Labels: no changelog, SLO

#1240 fix OAuth2 credentials unit tests
  internal/credentials/oauth2_test.go
Labels: no changelog, CI, tests

#1237 * Added experimental `ydb.RegisterDsnParser` for register external custom DSN parser for `ydb.Open` and `sql.Open` driver constructor
  CHANGELOG.md
  driver.go
  dsn.go
  dsn_test.go
  internal/xsql/dsn.go
  options.go
  sql.go
  tests/integration/connection_secure_test.go
  tests/integration/connection_test.go
  tests/integration/connection_with_compression_test.go
  tests/integration/monitoring_test.go
  tests/integration/register_dsn_parser_test.go
  tests/integration/static_credentials_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/table_tx_lazy_test.go
Labels: database/sql

#1023 enable ifshort linter
  .golangci.yml
  CHANGELOG.md
  examples/basic/native/table/series.go
  examples/decimal/decimal.go
  examples/read_table/orders.go
  examples/serverless/url_shortener/service.go
  examples/topic/cdc-cache-bus-freeseats/main.go
  internal/conn/conn.go
  internal/coordination/conversation/conversation.go
  internal/decimal/decimal.go
  internal/query/client.go
  internal/table/scanner/result.go
  internal/table/scanner/scan_raw.go
  internal/table/scanner/scanner.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/topic/topicwriterinternal/message.go
  internal/topic/topicwriterinternal/writer_reconnector.go
  internal/topic/topicwriterinternal/writer_single_stream.go
  internal/xsql/tx.go
  tests/slo/internal/config/config.go
  tests/slo/internal/generator/generator.go
  tests/slo/native/table/storage.go
  testutil/compare.go
  testutil/compare_test.go
Labels: refactoring

#1241 * Downgraded minimal version of Go to 1.20
  .github/workflows/breaking.yml
  .github/workflows/check-codegen.yml
  .github/workflows/examples.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  internal/pool/pool_test.go
  internal/topic/topicreaderinternal/stream_reconnector.go
  internal/xcontext/done.go
  internal/xcontext/done_test.go
  internal/xcontext/without_deadline.go
  internal/xcontext/without_deadline_go1.20.go
  internal/xsync/last_usage_guard.go
  internal/xsync/last_usage_guard_start.go
  internal/xsync/last_usage_guard_start_go1.20.go
Labels: refactoring, CI

#1244 * Added `query.ReadRow` method for execute query and read only one ro…
  CHANGELOG.md
  internal/query/client.go
  internal/query/client_test.go
  internal/query/errors.go
  internal/query/result.go
  internal/xcontext/done_go1.20.go
  log/query.go
  query/client.go
  query/example_test.go
  tests/integration/query_read_row_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: query-service
