Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-06, with the labels that each got.

#1249 * Added experimental query client helpers
  CHANGELOG.md
  internal/query/client.go
  internal/query/client_test.go
  internal/query/errors.go
  internal/query/result.go
  internal/query/result_set.go
  internal/query/result_test.go
  internal/query/row.go
  internal/query/scanner/data.go
  internal/query/scanner/errors.go
  internal/query/scanner/named_test.go
  internal/query/scanner/struct.go
  internal/query/scanner/struct_test.go
  internal/query/session.go
  internal/query/transaction.go
  log/query.go
  query/client.go
  query/example_test.go
  query/session.go
  query/transaction.go
  sugar/example_test.go
  sugar/query.go
  sugar/query_test.go
  tests/integration/sugar_unmarhall_result_set_test.go
  tests/integration/sugar_unmarhall_row_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: enhancement, query-service

#1251 * Added experimental method `query/Client.Execute` for execute query …
  CHANGELOG.md
  internal/query/client.go
  internal/query/client_test.go
  internal/query/execute_query_test.go
  internal/query/result.go
  internal/query/result_test.go
  query/client.go
  sugar/query_test.go
  tests/integration/query_execute_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: query-service

#1254 Enable funlen linter (part 8)
  internal/table/client.go
  internal/xsql/conn.go
  sugar/path.go
Labels: no changelog

#1256 * Added `query/ResultSet.{Columns,ColumnTypes}` methods for get column names and types from query result set
  CHANGELOG.md
  internal/query/result.go
  internal/query/result_set.go
  internal/query/result_set_test.go
  query/result.go
  sugar/query_test.go
  tests/integration/query_tx_execute_test.go
Labels: enhancement, query-service

#1259 * Excluded `Query()` method from interface `ydb.Connection`. Method `Query()` remains accessible from `ydb.Driver`
  CHANGELOG.md
  connection.go
  driver.go
Labels: refactoring

#1260 Added `retry.DoWithResult` and `retry.DoTxWithResult`
  CHANGELOG.md
  internal/query/scanner/named.go
  internal/query/scanner/named_test.go
  query/result.go
  retry/retry.go
  retry/sql.go
Labels: enhancement, refactoring

#1261 * Changed `query.DefaultTxControl()` from `quury.SerializableReadWrite()` with commit to `query.NoTx()`
  CHANGELOG.md
  query/transaction.go
Labels: refactoring, query-service

#1263 added test for internal/value.CastTo()
  internal/value/cast.go
  internal/value/cast_test.go
  internal/value/errors.go
Labels: query-service

#1267 remove query.bothDoAndDoTxOption
  internal/query/options/retry.go
  query/client.go
Labels: no changelog, refactoring, query-service

#1264 fix goroutine labels
  internal/topic/topicreaderinternal/committer.go
  internal/topic/topicreaderinternal/committer_test.go
  internal/topic/topicreaderinternal/stream_reader_impl.go
  internal/topic/topicwriterinternal/writer_single_stream.go
Labels: no changelog

#1270 Add more tests for cast.
  internal/query/scanner/indexed_test.go
  internal/query/scanner/named_test.go
  internal/query/scanner/struct_test.go
  internal/value/cast_test.go
  internal/value/value.go
Labels: no changelog, query-service

#1266 Added public types for `tx.Option` and `options.DoOption`
  CHANGELOG.md
  query/client.go
  query/transaction.go
Labels: query-service

#1268 * Added experimental range functions to the `query.Result` and `query.ResultSet` types, available starting with Go version 1.22. These features can be enabled by setting the environment variable `GOEXPERIMENT=rangefunc`.
  .github/workflows/tests.yml
  CHANGELOG.md
  internal/query/range_experiment.go
  internal/query/result.go
  internal/query/result_range_test.go
  internal/query/result_set.go
  internal/query/result_set_range_test.go
  internal/xiter/xiter.go
  internal/xiter/xiter_experiment_go1.22.go
  query/example_test.go
  query/result.go
  tests/integration/query_range_test.go
Labels: enhancement, query-service

#1278 * Removed public `query.Identifier` interface for exclude any external implementations for use with YDB
  CHANGELOG.md
  internal/query/execute_query_test.go
  internal/query/session_test.go
  internal/query/transaction.go
  internal/query/tx/control.go
  internal/query/tx/id.go
  query/transaction.go
Labels: refactoring, query-service

#1281 * Allowed the use of DSN without specifying the protocol/scheme
  CHANGELOG.md
  internal/dsn/dsn.go
  internal/dsn/dsn_test.go
Labels: bug, enhancement, refactoring

#1280 fix cast int* to uint*
  CHANGELOG.md
  internal/value/value.go
  internal/value/value_test.go
Labels: bug, refactoring

#1283 added description to error message if scan failed
  CHANGELOG.md
  internal/query/scanner/indexed.go
  internal/query/scanner/indexed_test.go
  internal/query/scanner/named.go
  internal/query/scanner/named_test.go
  internal/query/scanner/struct.go
  internal/query/scanner/struct_test.go
  internal/value/errors.go
  internal/value/value.go
Labels: refactoring

#1286 PreferLocations is pure function now
  CHANGELOG.md
  balancers/balancers.go
  internal/xslices/clone.go
  internal/xslices/clone_1.20.go
Labels: enhancement

#1284 * Diabled check the node is available for query service session
  CHANGELOG.md
  internal/balancer/balancer.go
  internal/query/client.go
  internal/query/session.go
  internal/table/client.go
  internal/table/client_test.go
  internal/table/errors.go
  internal/table/session.go
  testutil/driver.go
Labels: query-service

#1288 * Added `balancers.WithNodeID()` context modifier for define per request the YDB endpoint by NodeID
  CHANGELOG.md
  balancers/context.go
  internal/balancer/connections_state.go
  internal/balancer/connections_state_test.go
  internal/balancer/ctx.go
  internal/endpoint/context.go
  internal/endpoint/endpoint.go
  internal/table/session.go
Labels: enhancement

#1289 * Reverted the allowing the casts from signed YDB types to unsigned d…
  CHANGELOG.md
  internal/value/value.go
  internal/value/value_test.go
Labels: bug

#1290 * Replaced internal query session pool by default to stub for exclude impact from internal/pool
  CHANGELOG.md
  internal/query/client.go
  internal/query/config/config.go
  tests/integration/query_execute_test.go
Labels: bug, query-service

#1294 wrapped error BAD_SESSION in query session calls
  internal/query/config/config.go
  internal/query/session.go
  internal/query/transaction.go
Labels: bug, no changelog, query-service

#1296 Fix panic when database is nil.
  tests/integration/sugar_unmarhall_result_set_test.go
  tests/integration/table_tx_lazy_test.go
Labels: no changelog

#1297 schedule run tests
  .github/workflows/tests.yml
Labels: no changelog

#1298 fix race between logger in tests
  internal/xtest/logger.go
  tests/integration/basic_example_native_test.go
  tests/integration/connection_secure_test.go
  tests/integration/connection_test.go
  tests/integration/connection_with_compression_test.go
  tests/integration/discovery_test.go
  tests/integration/helpers_test.go
  tests/integration/metrics_registry_test.go
  tests/integration/ratelimiter_test.go
  tests/integration/scripting_test.go
  tests/integration/table_create_table_description_test.go
  tests/integration/table_create_table_partitions_test.go
  tests/integration/table_long_stream_test.go
  tests/integration/table_multiple_result_sets_test.go
  tests/integration/topic_read_writer_test.go
Labels: no changelog

#1299 fixed race on test logs
  internal/topic/topicwriterinternal/writer_reconnector_test.go
Labels: no changelog, flaky

#1300 * Fixed bug with fail cast of grpc response to `operation.{Response,Status}`
  CHANGELOG.md
  internal/conn/conn.go
  internal/conn/conn_test.go
  internal/conn/grpc_client_conn_interface_mock_test.go
  internal/conn/grpc_client_stream.go
  internal/grpcwrapper/rawtopic/describe_topic.go
  internal/operation/response.go
  internal/wrap/wrap.go
Labels: bug

#1303 Added codecov token from secrets
  .github/workflows/tests.yml
Labels: CI, tests
