Repository ydb-platform/ydb-go-sdk, pull requests merged in 2024-01, with the labels that each got.

#1002 enable dupword linter
  .golangci.yml
  internal/topic/topicreaderinternal/decoders.go
  topic/topicsugar/topicreader.go
Labels: no changelog

#1004 * The minimum version of Go in `ydb-go-sdk` has been raised to `go1.20`
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  internal/allocator/allocator.go
  internal/allocator/allocator_go1.18.go
  internal/xatomic/type.go
  internal/xatomic/type_go1.19.go
  internal/xbytes/clone.go
  internal/xbytes/clone_go1.20.go
  internal/xsql/badconn/badconn.go
  internal/xsql/badconn/badconn_go1.18.go
  internal/xsql/badconn/badconn_test.go
  internal/xsql/unwrap.go
  internal/xsql/unwrap_go1.18.go
  internal/xstring/convert.go
  internal/xstring/convert_go1.20.go
  retry/errors.go
  retry/errors_go1.18.go
  retry/sql_test.go
  sql_unwrap.go
  sql_unwrap_go1.18.go
  sugar/params.go
  sugar/params_go1.18.go
  sugar/params_go1.18_test.go
  sugar/params_test.go
  tests/integration/metrics_registry_go1.18_test.go
  tests/integration/metrics_registry_test.go
Labels: dependencies

#999 switch mock to uber fork of gomock
  .github/workflows/check-codegen.yml
  go.mod
  go.sum
  internal/topic/topicreaderinternal/batched_stream_reader_mock_test.go
  internal/topic/topicreaderinternal/message_content_pool_test.go
  internal/topic/topicreaderinternal/pool_interface_mock_test.go
  internal/topic/topicreaderinternal/raw_topic_reader_stream_mock_test.go
  internal/topic/topicreaderinternal/reader_test.go
  internal/topic/topicreaderinternal/stream_reader_impl_test.go
  internal/topic/topicreaderinternal/stream_reconnector_test.go
  internal/topic/topicwriterinternal/raw_topic_writer_stream_mock_test.go
  internal/topic/topicwriterinternal/writer_reconnector_test.go
  internal/topic/topicwriterinternal/writer_stream_interface_mock_test.go
  internal/topic/topicwriterinternal/writer_test.go
Labels: no changelog, no slo

#1005 Update LICENSE
  LICENSE
Labels: documentation, no changelog

#1008 enabled goconst
  .golangci.yml
  internal/bind/numeric_args.go
  internal/xstring/convert_bench_test.go
  tests/slo/database/sql/storage.go
  tests/slo/native/storage.go
  topic/example_test.go
Labels: no changelog, no slo

#1009 enabled testifylint
  .golangci.yml
  internal/conn/error_test.go
  internal/meta/trace_id_test.go
  internal/table/client_test.go
  internal/table/scanner/result_test.go
  internal/topic/topicreaderinternal/reader_test.go
  internal/topic/topicwriterinternal/writer_reconnector_test.go
  internal/xerrors/transport_test.go
  internal/xsync/event_broadcast_test.go
  log/logger_test.go
  table/options/models_test.go
  table/options/options_test.go
Labels: no changelog, no slo

#1016 * Supported column name prefix `__discard_column_` for discard columns in result sets
  CHANGELOG.md
  internal/xsql/rows.go
  tests/integration/database_sql_ignore_placeholder_test.go
Labels: enhancement

#1019 Enable temporary disabled tests
  tests/integration/topic_read_writer_test.go
Labels: no changelog
