Repository ydb-platform/ydb-go-sdk, pull requests merged in 2025-03, with the labels that each got.

#1667 Reverted implementation of internal/xcontext.WithDone
  internal/xcontext/done.go
  internal/xcontext/done_test.go
Labels: no changelog, refactoring

#1670 * Fixed bug with concurrent rewrites source slice of `grpc.DialOption` on dial step
  CHANGELOG.md
  internal/conn/conn.go
Labels: bug

#1671 fixed cleanup for database/sql driver
  tests/integration/database_sql_metrics_test.go
  tests/integration/helpers_test.go
Labels: no changelog, CI, database/sql, no slo

#1672 added internal/xtest.CheckGoroutinesLeak
  internal/xtest/leak.go
  internal/xtest/leak_test.go
  tests/integration/basic_example_database_sql_bindings_test.go
  tests/integration/basic_example_database_sql_test.go
  tests/integration/helpers_test.go
Labels: no changelog, CI, tests

#1674 Small changes in detector goroutines leak
  internal/xtest/leak.go
  internal/xtest/leak_test.go
Labels: no changelog, CI, no slo

#1680 move default constants fo internal, mark them deprecated
  config/defaults.go
  driver_string_test.go
  internal/config/defaults.go
Labels: no changelog, no slo, no tests

#1686 Close stream result
  internal/query/result.go
  internal/query/transaction_test.go
  internal/xtest/leak.go
Labels: no changelog, refactoring

#1687 * Fixed panic on closing `internal/query/sessionCore.done` channel twice
  CHANGELOG.md
  internal/query/session_core.go
  internal/query/session_core_test.go
Labels: bug

#1688 * Removed comment `experimental` from `ydb.ParamsBuilder` and `ydb.ParamsFromMap`
  CHANGELOG.md
  params_builder.go
  params_map.go
Labels: no slo, no tests

#1690 * Added `query.TransactionActor` type alias to `query.TxActor` for compatibility with `table.Client` API's
  CHANGELOG.md
  query/transaction.go
Labels: no slo, query-service, no tests

#1689 * Switched internal type of result `ydb.Driver.Query()` from `*internal/query.Client` to `query.Client` interface
  CHANGELOG.md
  driver.go
  dsn_test.go
  internal/query/client.go
  internal/xsql/conn_helpers.go
  internal/xsql/connector.go
  internal/xsql/xquery/conn.go
  internal/xsql/xtable/conn.go
  sql.go
Labels: query-service

#1691 * Supported wide `Date32`, `Datetime64` and `Timestamp64` types
  CHANGELOG.md
  internal/params/parameters.go
  internal/types/types.go
  internal/value/time.go
  internal/value/value.go
  internal/value/value_test.go
  tests/integration/query_execute_test.go
Labels: enhancement, query-service

#1693 * Supported wide `Interval64` type
  CHANGELOG.md
  internal/params/parameters.go
  internal/types/types.go
  internal/value/time.go
  internal/value/value.go
  tests/integration/query_execute_test.go
Labels: no slo

#1695 * Added binding `ydb.WithWideTimeTypes()` which interprets `time.Time` and `time.Duration` as `Timestamp64` and `Interval64` YDB types
  CHANGELOG.md
  dsn.go
  dsn_test.go
  internal/bind/auto_declare.go
  internal/bind/bind.go
  internal/bind/noop.go
  internal/bind/numeric_args.go
  internal/bind/numeric_args_test.go
  internal/bind/params.go
  internal/bind/params_test.go
  internal/bind/positional_args.go
  internal/bind/positional_args_test.go
  internal/bind/sql_lexer.go
  internal/bind/table_path_prefix.go
  internal/bind/wide_time_types.go
  internal/bind/wide_time_types_test.go
  internal/params/builder.go
  internal/params/parameters.go
  internal/value/value.go
  query_bind_test.go
  sql.go
Labels: enhancement

#1697 * Added bindings elipsis into `ydb.ParamsFromMap` for bind wide time types
  CHANGELOG.md
  dsn.go
  dsn_test.go
  internal/bind/bind.go
  internal/bind/errors.go
  internal/bind/wide_time_types.go
  internal/bind/wide_time_types_test.go
  internal/xsql/options.go
  params_map.go
  params_test.go
  query_bind_test.go
  sql.go
Labels: wide time types

#1698 * Changed argument types in `table.Client.ReadRows` to public types for compatibility with mock-generation
  CHANGELOG.md
  table/table.go
Labels: table

#1701 * Added query client session pool metrics: create_in_progress, in_use, waiters_queue + Added pool item closing for not-alived item
  CHANGELOG.md
  internal/pool/pool.go
  internal/pool/pool_test.go
  metrics/query.go
Labels: bug, tests, metrics, query-service, pool

#1702 added 24.4 and 25.1 ydb versions to integration tests
  .github/workflows/tests.yml
Labels: no changelog, no slo

#1705 Added TestInteractiveTx test
  tests/integration/tx_test.go
Labels: no changelog, tests, tx

#1706 Single implementation for transaction control
  CHANGELOG.md
  internal/allocator/allocator.go
  internal/query/client.go
  internal/query/client_test.go
  internal/query/execute_query.go
  internal/query/options/execute.go
  internal/query/options/execute_test.go
  internal/query/options/retry.go
  internal/query/transaction.go
  internal/query/tx/control.go
  internal/query/tx/settings.go
  internal/table/session.go
  internal/table/statement.go
  internal/table/transaction.go
  internal/tx/context.go
  internal/tx/control.go
  internal/tx/control_test.go
  internal/tx/settings.go
  internal/xsql/common/context.go
  internal/xsql/xquery/conn.go
  internal/xsql/xquery/isolation.go
  internal/xsql/xquery/tx.go
  internal/xsql/xtable/conn.go
  internal/xsql/xtable/isolation.go
  internal/xsql/xtable/isolation_test.go
  internal/xsql/xtable/tx.go
  query/execute_options.go
  query/transaction.go
  sql.go
  table/table.go
  tests/integration/database_sql_with_tx_control_test.go
  tests/integration/query_regression_test.go
Labels: refactoring, tx

#1711 Params
  CHANGELOG.md
  params_builder.go
Labels: no changelog, params-builder
