Repository ydb-platform/ydb-go-sdk, pull requests merged in 2025-02, with the labels that each got.

#1631 added `xsync.Slice`
  internal/xsync/slice.go
  internal/xsync/slice_test.go
Labels: no changelog, internal

#1629 * Fixed goroutine leak on closing `database/sql` driver
  CHANGELOG.md
  driver.go
  internal/repeater/repeater.go
  internal/xsql/connector.go
  internal/xsql/options.go
  sql.go
  tests/integration/basic_example_database_sql_bindings_test.go
  tests/integration/basic_example_database_sql_test.go
  tests/integration/helpers_test.go
Labels: database/sql

#1632 check context before call session close
  CHANGELOG.md
  internal/query/session_core.go
  internal/table/retry_test.go
  internal/table/session.go
  internal/xsql/connector.go
  internal/xsql/errors.go
  tests/integration/basic_example_database_sql_test.go
Labels: bug, refactoring

#1639 * Fixed deadlock on closing table session with internal query session core
  CHANGELOG.md
  internal/table/session.go
Labels: query-service, drop-in replacement

#1640 remove xsync.slice. It isn't using now, but have potential bug in interface.
  internal/xsync/slice.go
  internal/xsync/slice_test.go
Labels: no changelog, no slo

#1644 remove no need nil check
  internal/topic/topiclistenerinternal/stream_listener.go
Labels: no changelog

#1616 improve logging
  CHANGELOG.md
  internal/topic/topicwriterinternal/writer_single_stream.go
  log/coordination.go
  log/discovery.go
  log/driver.go
  log/query.go
  log/retry.go
  log/scripting.go
  log/sql.go
  log/table.go
  log/topic.go
Labels: no slo, no tests

#1647 * Returned legacy behaviour for interpret as `time.Time` YDB types `Date`, `Datetime` and `Timestamp`
  CHANGELOG.md
  internal/value/any.go
  internal/value/any_test.go
Labels: refactoring

#1646 supress continueslu linter warnings
  internal/balancer/balancer.go
  internal/conn/conn.go
Labels: no changelog, no slo, no tests

#1651 * Added stacktrace call to row scan errors for detect broken client code
  CHANGELOG.md
  internal/query/row.go
  internal/query/row_test.go
Labels: query-service

#1656 Added debug mark for attach sessions
  internal/query/session_core.go
Labels: no changelog

#1657 added go1.24 to CI
  .github/workflows/breaking.yml
  .github/workflows/check-codegen.yml
  .github/workflows/examples.yml
  .github/workflows/lint.yml
  .github/workflows/slo.yml
  .github/workflows/tests.yml
Labels: no changelog, CI

#1658 Pool error handling
  CHANGELOG.md
  internal/pool/pool.go
  internal/pool/pool_test.go
  internal/query/client_test.go
  internal/table/retry_test.go
Labels: pool

#1659 refactoring of attach stream goroutine label
  internal/query/session_core.go
Labels: no changelog

#1664 small changes in logs
  log/driver.go
Labels: no changelog, no slo, no tests

#1663 Extracted logic of checking error for delete session from retry.Retry
  CHANGELOG.md
  internal/coordination/client_test.go
  internal/coordination/errors.go
  internal/pool/pool.go
  internal/pool/pool_test.go
  internal/query/client.go
  internal/query/transaction.go
  internal/table/client.go
  internal/table/retry.go
  internal/table/retry_test.go
  internal/table/session.go
  internal/table/transaction.go
  internal/xerrors/check.go
  internal/xerrors/operation.go
  internal/xerrors/retryable.go
  internal/xerrors/retryable_test.go
  internal/xerrors/session.go
  internal/xerrors/session_test.go
  internal/xerrors/transport.go
  internal/xerrors/xerrors.go
  internal/xsql/badconn/badconn.go
  internal/xsql/badconn/badconn_test.go
  internal/xsql/conn.go
  internal/xsql/errors.go
  internal/xsql/stmt.go
  internal/xsql/tx.go
  internal/xsql/unwrap.go
  internal/xsql/xquery/conn.go
  internal/xsql/xquery/errors.go
  internal/xsql/xquery/tx_fake.go
  internal/xsql/xtable/conn.go
  internal/xsql/xtable/errors.go
  internal/xsql/xtable/rows.go
  internal/xsql/xtable/tx.go
  internal/xsql/xtable/tx_fake.go
  retry/errors.go
  retry/errors_data_test.go
  retry/mode.go
  retry/retry.go
  retry/retry_test.go
  retry/retryable_error.go
  retry/sql.go
  retry/sql_test.go
  tests/integration/database_sql_regression_test.go
  tests/integration/retryable_error_with_invalid_object_test.go
  trace/query.go
  trace/query_gtrace.go
Labels: no changelog, refactoring

#1665 * Fixed bug in `internal/xcontext.WithDone` (not listening chan done)
  CHANGELOG.md
  internal/xcontext/done.go
  internal/xcontext/done_test.go
Labels: bug
