Repository ydb-platform/ydb-go-sdk, pull requests merged in 2025-01, with the labels that each got.

#1606 improve comments
  topic/topicreader/reader.go
Labels: no changelog, no slo, no tests

#1609 processing of panics in retriers
  retry/sql.go
  retry/sql_test.go
Labels: no changelog

#1610 refactored query stats: implemetation instead interface
  CHANGELOG.md
  internal/stats/query.go
  internal/stats/query_go1.23_test.go
  internal/xiter/xiter.go
  internal/xiter/xiter_go1.23.go
Labels: no slo

#1614 dedicaded close message for internal balancer closed
  internal/balancer/balancer.go
Labels: no changelog

#1621 bumped jwt/v4
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  tests/slo/go.sum
Labels: no changelog, dependencies

#1627 fixed issue 'Explicit null dereferenced' (CWE-476)
  CHANGELOG.md
  internal/credentials/errors.go
  internal/credentials/errors_test.go
  internal/credentials/static.go
Labels: bug
