Repository ydb-platform/ydb-go-sdk, pull requests merged in 2025-07, with the labels that each got.

#1817 fixed redundant defer in sessionCore.closeOnce
  internal/query/session_core.go
Labels: no changelog

#1841 * Marked as non-retryable operation error `ABORTED` with internal issue `200509` ("Datashard program size limit exceeded")
  CHANGELOG.md
  internal/xerrors/issues.go
  internal/xerrors/issues_test.go
  internal/xerrors/operation.go
  internal/xerrors/operation_test.go
  retry/errors_data_test.go
Labels: bug

#1840 Failover unit test for DNS with unavailable IP addresses
  internal/balancer/balancer_test.go
Labels: no changelog, no slo, no examples
