Repository ydb-platform/ydb-go-sdk, pull requests merged in 2025-06, with the labels that each got.

#1807 skip test for nigtly version for bug workaround
  tests/integration/topic_read_writer_test.go
Labels: no changelog, no slo, no examples

#1808 set fixed golang version
  .github/workflows/lint.yml
Labels: no changelog, no slo, no tests, no examples

#1822 Fixed `github_token` variable in SLO-report workflow
  .github/workflows/slo-report.yml
Labels: no changelog, no slo, no tests
